/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package api




type ApplicationsApplicationScopes int64

// Enum ApplicationsApplicationScopes
const (
	ApplicationsApplicationScopes_1 ApplicationsApplicationScopes = 1
	ApplicationsApplicationScopes_2 ApplicationsApplicationScopes = 2
	ApplicationsApplicationScopes_4 ApplicationsApplicationScopes = 4
	ApplicationsApplicationScopes_8 ApplicationsApplicationScopes = 8
	ApplicationsApplicationScopes_16 ApplicationsApplicationScopes = 16
	ApplicationsApplicationScopes_32 ApplicationsApplicationScopes = 32
	ApplicationsApplicationScopes_64 ApplicationsApplicationScopes = 64
	ApplicationsApplicationScopes_128 ApplicationsApplicationScopes = 128
	ApplicationsApplicationScopes_256 ApplicationsApplicationScopes = 256
	ApplicationsApplicationScopes_512 ApplicationsApplicationScopes = 512
	ApplicationsApplicationScopes_1024 ApplicationsApplicationScopes = 1024
)


