/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package api

import (
	"time"
)




type CommunityCommunityLiveStatus struct {
	
	DateStatusUpdated time.Time `json:"dateStatusUpdated,omitempty"`
	
	Url string `json:"url,omitempty"`
	
	PartnershipIdentifier string `json:"partnershipIdentifier,omitempty"`
	
	PartnershipType *PartnershipsPartnershipType `json:"partnershipType,omitempty"`
	
	Thumbnail string `json:"thumbnail,omitempty"`
	
	ThumbnailSmall string `json:"thumbnailSmall,omitempty"`
	
	ThumbnailLarge string `json:"thumbnailLarge,omitempty"`
	
	DestinyCharacterId int64 `json:"destinyCharacterId,omitempty"`
	
	UserInfo *UserUserInfoCard `json:"userInfo,omitempty"`
	
	CurrentActivityHash int32 `json:"currentActivityHash,omitempty"`
	
	DateLastPlayed time.Time `json:"dateLastPlayed,omitempty"`
	
	DateStreamStarted time.Time `json:"dateStreamStarted,omitempty"`
	
	Locale string `json:"locale,omitempty"`
	
	CurrentViewers int32 `json:"currentViewers,omitempty"`
	
	Followers int32 `json:"followers,omitempty"`
	
	OverallViewers int32 `json:"overallViewers,omitempty"`
	
	IsFeatured bool `json:"isFeatured,omitempty"`
	
	Title string `json:"title,omitempty"`
	
	ActivityModeHash int32 `json:"activityModeHash,omitempty"`
	
	DateFeatured time.Time `json:"dateFeatured,omitempty"`
	
	TrendingValue float32 `json:"trendingValue,omitempty"`
	
	IsSubscribable bool `json:"isSubscribable,omitempty"`
}

