/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package api




type CommunityCommunityStatusSort int32

// Enum CommunityCommunityStatusSort
const (
	CommunityCommunityStatusSort_0 CommunityCommunityStatusSort = 0
	CommunityCommunityStatusSort_1 CommunityCommunityStatusSort = 1
	CommunityCommunityStatusSort_2 CommunityCommunityStatusSort = 2
	CommunityCommunityStatusSort_3 CommunityCommunityStatusSort = 3
)


