/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package api

import (
	"time"
)




type ContentContentItemPublicContract struct {
	
	ContentId int64 `json:"contentId,omitempty"`
	
	CType string `json:"cType,omitempty"`
	
	CmsPath string `json:"cmsPath,omitempty"`
	
	CreationDate time.Time `json:"creationDate,omitempty"`
	
	ModifyDate time.Time `json:"modifyDate,omitempty"`
	
	AllowComments bool `json:"allowComments,omitempty"`
	
	HasAgeGate bool `json:"hasAgeGate,omitempty"`
	
	MinimumAge int32 `json:"minimumAge,omitempty"`
	
	RatingImagePath string `json:"ratingImagePath,omitempty"`
	
	Author *UserGeneralUser `json:"author,omitempty"`
	
	AutoEnglishPropertyFallback bool `json:"autoEnglishPropertyFallback,omitempty"`
	// Firehose content is really a collection of metadata and \"properties\", which are the potentially-but-not-strictly localizable data that comprises the meat of whatever content is being shown.  As Cole Porter would have crooned, \"Anything Goes\" with Firehose properties. They are most often strings, but they can theoretically be anything. They are JSON encoded, and could be JSON structures, simple strings, numbers etc... The Content Type of the item (cType) will describe the properties, and thus how they ought to be deserialized.
	Properties map[string]interface{} `json:"properties,omitempty"`
	
	Representations []ContentContentRepresentation `json:"representations,omitempty"`
	
	Tags []string `json:"tags,omitempty"`
	
	CommentSummary *ContentCommentSummary `json:"commentSummary,omitempty"`
}

