/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package api





type ContentContentRepresentation struct {
	
	Name string `json:"name,omitempty"`
	
	Path string `json:"path,omitempty"`
	
	ValidationString string `json:"validationString,omitempty"`
}

