/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package api




// The definition for an \"inventory flyout\": a UI screen where we show you part of an otherwise hidden vendor inventory: like the Vault inventory buckets.
type DestinyDefinitionsDestinyVendorInventoryFlyoutDefinition struct {
	// If the flyout is locked, this is the reason why.
	LockedDescription string `json:"lockedDescription,omitempty"`
	// The title and other common properties of the flyout.
	DisplayProperties *interface{} `json:"displayProperties,omitempty"`
	// A list of inventory buckets and other metadata to show on the screen.
	Buckets []DestinyDefinitionsDestinyVendorInventoryFlyoutBucketDefinition `json:"buckets,omitempty"`
	// An identifier for the flyout, in case anything else needs to refer to them.
	FlyoutId int32 `json:"flyoutId,omitempty"`
	// If this is true, don't show any of the glistening \"this is a new item\" UI elements, like we show on the inventory items themselves in in-game UI.
	SuppressNewness bool `json:"suppressNewness,omitempty"`
}

