/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package api




type DestinyVendorItemStatus int32

// Enum DestinyVendorItemStatus
const (
	DestinyVendorItemStatus_0 DestinyVendorItemStatus = 0
	DestinyVendorItemStatus_1 DestinyVendorItemStatus = 1
	DestinyVendorItemStatus_2 DestinyVendorItemStatus = 2
	DestinyVendorItemStatus_4 DestinyVendorItemStatus = 4
	DestinyVendorItemStatus_8 DestinyVendorItemStatus = 8
	DestinyVendorItemStatus_16 DestinyVendorItemStatus = 16
	DestinyVendorItemStatus_32 DestinyVendorItemStatus = 32
	DestinyVendorItemStatus_64 DestinyVendorItemStatus = 64
	DestinyVendorItemStatus_128 DestinyVendorItemStatus = 128
	DestinyVendorItemStatus_256 DestinyVendorItemStatus = 256
	DestinyVendorItemStatus_512 DestinyVendorItemStatus = 512
	DestinyVendorItemStatus_1024 DestinyVendorItemStatus = 1024
	DestinyVendorItemStatus_2048 DestinyVendorItemStatus = 2048
	DestinyVendorItemStatus_4096 DestinyVendorItemStatus = 4096
)


