/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package api




// Represents a reference to a Challenge, which for now is just an Objective.
type DestinyDefinitionsDestinyActivityChallengeDefinition struct {
	// The hash for the Objective that matches this challenge. Use it to look up the DestinyObjectiveDefinition.
	ObjectiveHash int32 `json:"objectiveHash,omitempty"`
}

