/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package api



// DestinyDestinyActivityDifficultyTier : An enumeration representing the potential difficulty levels of an activity. Their names are... more qualitative than quantitative.
type DestinyDestinyActivityDifficultyTier int32

// Enum DestinyDestinyActivityDifficultyTier
const (
	DestinyDestinyActivityDifficultyTier_0 DestinyDestinyActivityDifficultyTier = 0
	DestinyDestinyActivityDifficultyTier_1 DestinyDestinyActivityDifficultyTier = 1
	DestinyDestinyActivityDifficultyTier_2 DestinyDestinyActivityDifficultyTier = 2
	DestinyDestinyActivityDifficultyTier_3 DestinyDestinyActivityDifficultyTier = 3
	DestinyDestinyActivityDifficultyTier_4 DestinyDestinyActivityDifficultyTier = 4
	DestinyDestinyActivityDifficultyTier_5 DestinyDestinyActivityDifficultyTier = 5
	DestinyDestinyActivityDifficultyTier_6 DestinyDestinyActivityDifficultyTier = 6
	DestinyDestinyActivityDifficultyTier_7 DestinyDestinyActivityDifficultyTier = 7
)


