/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package api




// Destinations and Activities may have default Activity Graphs that should be shown when you bring up the Director and are playing in either.  This contract defines the graph referred to and the gating for when it is relevant.
type DestinyDefinitionsDestinyActivityGraphListEntryDefinition struct {
	// The hash identifier of the DestinyActivityGraphDefinition that should be shown when opening the director.
	ActivityGraphHash int32 `json:"activityGraphHash,omitempty"`
}

