/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package api




type DestinyDefinitionsDestinyTalentNodeStepImpactEffects int32

// Enum DestinyDefinitionsDestinyTalentNodeStepImpactEffects
const (
	DestinyDefinitionsDestinyTalentNodeStepImpactEffects_0 DestinyDefinitionsDestinyTalentNodeStepImpactEffects = 0
	DestinyDefinitionsDestinyTalentNodeStepImpactEffects_1 DestinyDefinitionsDestinyTalentNodeStepImpactEffects = 1
	DestinyDefinitionsDestinyTalentNodeStepImpactEffects_2 DestinyDefinitionsDestinyTalentNodeStepImpactEffects = 2
	DestinyDefinitionsDestinyTalentNodeStepImpactEffects_4 DestinyDefinitionsDestinyTalentNodeStepImpactEffects = 4
	DestinyDefinitionsDestinyTalentNodeStepImpactEffects_8 DestinyDefinitionsDestinyTalentNodeStepImpactEffects = 8
	DestinyDefinitionsDestinyTalentNodeStepImpactEffects_16 DestinyDefinitionsDestinyTalentNodeStepImpactEffects = 16
	DestinyDefinitionsDestinyTalentNodeStepImpactEffects_32 DestinyDefinitionsDestinyTalentNodeStepImpactEffects = 32
	DestinyDefinitionsDestinyTalentNodeStepImpactEffects_63 DestinyDefinitionsDestinyTalentNodeStepImpactEffects = 63
)


