/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package api



// DestinyDestinyStatAggregationType : When a Stat (DestinyStatDefinition) is aggregated, this is the rules used for determining the level and formula used for aggregation.  * CharacterAverage = apply a weighted average using the related DestinyStatGroupDefinition on the DestinyInventoryItemDefinition across the character's equipped items. See both of those definitions for details. * Character = don't aggregate: the stat should be located and used directly on the character. * Item = don't aggregate: the stat should be located and used directly on the item.
type DestinyDestinyStatAggregationType int32

// Enum DestinyDestinyStatAggregationType
const (
	DestinyDestinyStatAggregationType_0 DestinyDestinyStatAggregationType = 0
	DestinyDestinyStatAggregationType_1 DestinyDestinyStatAggregationType = 1
	DestinyDestinyStatAggregationType_2 DestinyDestinyStatAggregationType = 2
)


