/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package api





type DestinyHistoricalStatsDestinyPostGameCarnageReportTeamEntry struct {
	// Integer ID for the team.
	TeamId int32 `json:"teamId,omitempty"`
	// Team's standing relative to other teams.
	Standing *interface{} `json:"standing,omitempty"`
	// Score earned by the team
	Score *interface{} `json:"score,omitempty"`
	// Alpha or Bravo
	TeamName string `json:"teamName,omitempty"`
}

