/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package api




// If the activity is a playlist, this is the definition for a specific entry in the playlist: a single possible combination of Activity and Activity Mode that can be chosen.
type DestinyDefinitionsDestinyActivityPlaylistItemDefinition struct {
	// The hash identifier of the Activity that can be played. Use it to look up the DestinyActivityDefinition.
	ActivityHash int32 `json:"activityHash,omitempty"`
	
	DirectActivityModeHash int32 `json:"directActivityModeHash,omitempty"`
	
	DirectActivityModeType int32 `json:"directActivityModeType,omitempty"`
	
	ActivityModeHashes []int32 `json:"activityModeHashes,omitempty"`
	
	ActivityModeTypes []DestinyHistoricalStatsDefinitionsDestinyActivityModeType `json:"activityModeTypes,omitempty"`
}

