/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package api





type DestinyHistoricalStatsDestinyHistoricalStatsByPeriod struct {
	
	AllTime map[string]DestinyHistoricalStatsDestinyHistoricalStatsValue `json:"allTime,omitempty"`
	
	AllTimeTier1 map[string]DestinyHistoricalStatsDestinyHistoricalStatsValue `json:"allTimeTier1,omitempty"`
	
	AllTimeTier2 map[string]DestinyHistoricalStatsDestinyHistoricalStatsValue `json:"allTimeTier2,omitempty"`
	
	AllTimeTier3 map[string]DestinyHistoricalStatsDestinyHistoricalStatsValue `json:"allTimeTier3,omitempty"`
	
	Daily []DestinyHistoricalStatsDestinyHistoricalStatsPeriodGroup `json:"daily,omitempty"`
	
	Monthly []DestinyHistoricalStatsDestinyHistoricalStatsPeriodGroup `json:"monthly,omitempty"`
}

