/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package api

import (
	"time"
)



// This component holds activity data for a character. It will tell you about the character's current activity status, as well as activities that are available to the user.
type DestinyEntitiesCharactersDestinyCharacterActivitiesComponent struct {
	// The last date that the user started playing an activity.
	DateActivityStarted time.Time `json:"dateActivityStarted,omitempty"`
	// The list of activities that the user can play.
	AvailableActivities []DestinyDestinyActivity `json:"availableActivities,omitempty"`
	// If the user is in an activity, this will be the hash of the Activity being played. Note that you must combine this info with currentActivityModeHash to get a real picture of what the user is doing right now. For instance, PVP \"Activities\" are just maps: it's the ActivityMode that determines what type of PVP game they're playing.
	CurrentActivityHash int32 `json:"currentActivityHash,omitempty"`
	// If the user is in an activity, this will be the hash of the activity mode being played. Combine with currentActivityHash to give a person a full picture of what they're doing right now.
	CurrentActivityModeHash int32 `json:"currentActivityModeHash,omitempty"`
	
	CurrentActivityModeType int32 `json:"currentActivityModeType,omitempty"`
	
	CurrentActivityModeHashes []int32 `json:"currentActivityModeHashes,omitempty"`
	
	CurrentActivityModeTypes []DestinyHistoricalStatsDefinitionsDestinyActivityModeType `json:"currentActivityModeTypes,omitempty"`
	
	CurrentPlaylistActivityHash int32 `json:"currentPlaylistActivityHash,omitempty"`
	// This will have the activity hash of the last completed story/campaign mission, in case you care about that.
	LastCompletedStoryHash int32 `json:"lastCompletedStoryHash,omitempty"`
}

