/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package api




// Data related to what happens while a plug is being inserted, mostly for UI purposes.
type DestinyDefinitionsSocketsDestinyInsertPlugActionDefinition struct {
	// How long it takes for the Plugging of the item to be completed once it is initiated, if you care.
	ActionExecuteSeconds int32 `json:"actionExecuteSeconds,omitempty"`
}

