/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package api




// This defines information that can only come from a talent grid on an item. Items mostly have negligible talent grid data these days, but instanced items still retain grids as a source for some of this common information.  Builds/Subclasses are the only items left that still have talent grids with meaningful Nodes.
type DestinyDefinitionsDestinyItemTalentGridBlockDefinition struct {
	// The hash identifier of the DestinyTalentGridDefinition attached to this item.
	TalentGridHash int32 `json:"talentGridHash,omitempty"`
	// This is meant to be a subtitle for looking at the talent grid. In practice, somewhat frustratingly, this always merely says the localized word for \"Details\". Great. Maybe it'll have more if talent grids ever get used for more than builds and subclasses again.
	ItemDetailString string `json:"itemDetailString,omitempty"`
	// A shortcut string identifier for the \"build\" in question, if this talent grid has an associated build. Doesn't map to anything we can expose at the moment.
	BuildName string `json:"buildName,omitempty"`
	// If the talent grid implies a damage type, this is the enum value for that damage type.
	HudDamageType *interface{} `json:"hudDamageType,omitempty"`
	// If the talent grid has a special icon that's shown in the game UI (like builds, funny that), this is the identifier for that icon. Sadly, we don't actually get that icon right now. I'll be looking to replace this with a path to the actual icon itself.
	HudIcon string `json:"hudIcon,omitempty"`
}

