/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package api



// DestinyDestinyObjectiveGrantStyle : Some Objectives provide perks, generally as part of providing some kind of interesting modifier for a Challenge or Quest. This indicates when the Perk is granted.
type DestinyDestinyObjectiveGrantStyle int32

// Enum DestinyDestinyObjectiveGrantStyle
const (
	DestinyDestinyObjectiveGrantStyle_0 DestinyDestinyObjectiveGrantStyle = 0
	DestinyDestinyObjectiveGrantStyle_1 DestinyDestinyObjectiveGrantStyle = 1
	DestinyDestinyObjectiveGrantStyle_2 DestinyDestinyObjectiveGrantStyle = 2
)


