/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package api



// DestinyActivityGraphNodeHighlightType : The various known UI styles in which an item can be highlighted. It'll be up to you to determine what you want to show based on this highlighting, BNet doesn't have any assets that correspond to these states. And yeah, RiseOfIron and Comet have their own special highlight states. Don't ask me, I can't imagine they're still used.
type DestinyActivityGraphNodeHighlightType int32

// Enum DestinyActivityGraphNodeHighlightType
const (
	DestinyActivityGraphNodeHighlightType_0 DestinyActivityGraphNodeHighlightType = 0
	DestinyActivityGraphNodeHighlightType_1 DestinyActivityGraphNodeHighlightType = 1
	DestinyActivityGraphNodeHighlightType_2 DestinyActivityGraphNodeHighlightType = 2
	DestinyActivityGraphNodeHighlightType_3 DestinyActivityGraphNodeHighlightType = 3
	DestinyActivityGraphNodeHighlightType_4 DestinyActivityGraphNodeHighlightType = 4
)


