/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package api



// DestinyDestinyActivityModeCategory : Activity Modes are grouped into a few possible broad categories.
type DestinyDestinyActivityModeCategory int32

// Enum DestinyDestinyActivityModeCategory
const (
	DestinyDestinyActivityModeCategory_0 DestinyDestinyActivityModeCategory = 0
	DestinyDestinyActivityModeCategory_1 DestinyDestinyActivityModeCategory = 1
	DestinyDestinyActivityModeCategory_2 DestinyDestinyActivityModeCategory = 2
)


