/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package api




type DestinyDestinyClass int32

// Enum DestinyDestinyClass
const (
	DestinyDestinyClass_0 DestinyDestinyClass = 0
	DestinyDestinyClass_1 DestinyDestinyClass = 1
	DestinyDestinyClass_2 DestinyDestinyClass = 2
	DestinyDestinyClass_3 DestinyDestinyClass = 3
)


