/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package api




// Defines the conditions under which stat modifications will be applied to a Character while participating in an objective.
type DestinyDefinitionsDestinyObjectiveStatEntryDefinition struct {
	// The stat being modified, and the value used.
	Stat *interface{} `json:"stat,omitempty"`
	// Whether it will be applied as long as the objective is active, when it's completed, or until it's completed.
	Style *interface{} `json:"style,omitempty"`
}

