/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package api




// So much of what you see in Destiny is actually an Item used in a new and creative way. This is the definition for Items in Destiny, which started off as just entities that could exist in your Inventory but ended up being the backing data for so much more: quests, reward previews, slots, and subclasses.  In practice, you will want to associate this data with \"live\" item data from a Bungie.Net Platform call: these definitions describe the item in generic, non-instanced terms: but an actual instance of an item can vary widely from these generic definitions.
type DestinyDefinitionsDestinyInventoryItemDefinition struct {
	
	DisplayProperties *DestinyDefinitionsCommonDestinyDisplayPropertiesDefinition `json:"displayProperties,omitempty"`
	// A secondary icon associated with the item. Currently this is used in very context specific applications, such as Emblem Nameplates.
	SecondaryIcon string `json:"secondaryIcon,omitempty"`
	// Pulled from the secondary icon, this is the \"secondary background\" of the secondary icon. Confusing? Sure, that's why I call it \"overlay\" here: because as far as it's been used thus far, it has been for an optional overlay image. We'll see if that holds up, but at least for now it explains what this image is a bit better.
	SecondaryOverlay string `json:"secondaryOverlay,omitempty"`
	// Pulled from the Secondary Icon, this is the \"special\" background for the item. For Emblems, this is the background image used on the Details view: but it need not be limited to that for other types of items.
	SecondarySpecial string `json:"secondarySpecial,omitempty"`
	// If we were able to acquire an in-game screenshot for the item, the path to that screenshot will be returned here. Note that not all items have screenshots: particularly not any non-equippable items.
	Screenshot string `json:"screenshot,omitempty"`
	// The localized title/name of the item's type. This can be whatever the designers want, and has no guarantee of consistency between items.
	ItemTypeDisplayName string `json:"itemTypeDisplayName,omitempty"`
	// It became a common enough pattern in our UI to show Item Type and Tier combined into a single localized string that I'm just going to go ahead and start pre-creating these for items.
	ItemTypeAndTierDisplayName string `json:"itemTypeAndTierDisplayName,omitempty"`
	// In theory, it is a localized string telling you about how you can find the item. I really wish this was more consistent. Many times, it has nothing. Sometimes, it's instead a more narrative-forward description of the item. Which is cool, and I wish all properties had that data, but it should really be its own property.
	DisplaySource string `json:"displaySource,omitempty"`
	// An identifier that the game UI uses to determine what type of tooltip to show for the item. These have no corresponding definitions that BNet can link to: so it'll be up to you to interpret and display your UI differently according to these styles (or ignore it).
	TooltipStyle string `json:"tooltipStyle,omitempty"`
	// If the item can be \"used\", this block will be non-null, and will have data related to the action performed when using the item. (Guess what? 99% of the time, this action is \"dismantle\". Shocker)
	Action *interface{} `json:"action,omitempty"`
	// If this item can exist in an inventory, this block will be non-null. In practice, every item that currently exists has one of these blocks. But note that it is not necessarily guaranteed.
	Inventory *interface{} `json:"inventory,omitempty"`
	// If this item is a quest, this block will be non-null. In practice, I wish I had called this the Quest block, but at the time it wasn't clear to me whether it would end up being used for purposes other than quests. It will contain data about the steps in the quest, and mechanics we can use for displaying and tracking the quest.
	SetData *interface{} `json:"setData,omitempty"`
	// If this item can have stats (such as a weapon, armor, or vehicle), this block will be non-null and populated with the stats found on the item.
	Stats *interface{} `json:"stats,omitempty"`
	// If this item can be equipped, this block will be non-null and will be populated with the conditions under which it can be equipped.
	EquippingBlock *interface{} `json:"equippingBlock,omitempty"`
	// If this item can be rendered, this block will be non-null and will be populated with rendering information.
	TranslationBlock *interface{} `json:"translationBlock,omitempty"`
	// If this item can be Used or Acquired to gain other items (for instance, how Eververse Boxes can be consumed to get items from the box), this block will be non-null and will give summary information for the items that can be acquired.
	Preview *interface{} `json:"preview,omitempty"`
	// If this item can have a level or stats, this block will be non-null and will be populated with default quality (item level, \"quality\", and infusion) data. See the block for more details, there's often less upfront information in D2 so you'll want to be aware of how you use quality and item level on the definition level now.
	Quality *interface{} `json:"quality,omitempty"`
	// The conceptual \"Value\" of an item, if any was defined. See the DestinyItemValueBlockDefinition for more details.
	Value *interface{} `json:"value,omitempty"`
	// If this item has a known source, this block will be non-null and populated with source information. Unfortunately, at this time we are not generating sources: that is some aggressively manual work which we didn't have time for, and I'm hoping to get back to at some point in the future.
	SourceData *interface{} `json:"sourceData,omitempty"`
	// If this item has Objectives (extra tasks that can be accomplished related to the item... most frequently when the item is a Quest Step and the Objectives need to be completed to move on to the next Quest Step), this block will be non-null and the objectives defined herein.
	Objectives *interface{} `json:"objectives,omitempty"`
	// If this item *is* a Plug, this will be non-null and the info defined herein. See DestinyItemPlugDefinition for more information.
	Plug *interface{} `json:"plug,omitempty"`
	// If this item has related items in a \"Gear Set\", this will be non-null and the relationships defined herein.
	Gearset *DestinyDefinitionsDestinyItemGearsetBlockDefinition `json:"gearset,omitempty"`
	// If this item is a \"reward sack\" that can be opened to provide other items, this will be non-null and the properties of the sack contained herein.
	Sack *interface{} `json:"sack,omitempty"`
	// If this item has any Sockets, this will be non-null and the individual sockets on the item will be defined herein.
	Sockets *interface{} `json:"sockets,omitempty"`
	// Summary data about the item.
	Summary *interface{} `json:"summary,omitempty"`
	// If the item has a Talent Grid, this will be non-null and the properties of the grid defined herein. Note that, while many items still have talent grids, the only ones with meaningful Nodes still on them will be Subclass/\"Build\" items.
	TalentGrid *interface{} `json:"talentGrid,omitempty"`
	// If the item has stats, this block will be defined. It has the \"raw\" investment stats for the item. These investment stats don't take into account the ways that the items can spawn, nor do they take into account any Stat Group transformations. I have retained them for debugging purposes, but I do not know how useful people will find them.
	InvestmentStats []DestinyDefinitionsDestinyItemInvestmentStatDefinition `json:"investmentStats,omitempty"`
	// If the item has any *intrinsic* Perks (Perks that it will provide regardless of Sockets, Talent Grid, and other transitory state), they will be defined here.
	Perks []DestinyDefinitionsDestinyItemPerkEntryDefinition `json:"perks,omitempty"`
	// If the item has any related Lore (DestinyLoreDefinition), this will be the hash identifier you can use to look up the lore definition.
	LoreHash uint32 `json:"loreHash,omitempty"`
	// There are times when the game will show you a \"summary/vague\" version of an item - such as a description of its type represented as a DestinyInventoryItemDefinition - rather than display the item itself.  This happens sometimes when summarizing possible rewards in a tooltip. This is the item displayed instead, if it exists.
	SummaryItemHash int32 `json:"summaryItemHash,omitempty"`
	// If any animations were extracted from game content for this item, these will be the definitions of those animations.
	Animations []DestinyDefinitionsAnimationsDestinyAnimationReference `json:"animations,omitempty"`
	// BNet may forbid the execution of actions on this item via the API. If that is occurring, allowActions will be set to false.
	AllowActions bool `json:"allowActions,omitempty"`
	// If we added any help or informational URLs about this item, these will be those links.
	Links []LinksHyperlinkReference `json:"links,omitempty"`
	// The intrinsic transferability of an item.  I hate that this boolean is negative - but there's a reason.  Just because an item is intrinsically transferrable doesn't mean that it can be transferred, and we don't want to imply that this is the only source of that transferability.
	NonTransferrable bool `json:"nonTransferrable,omitempty"`
	// BNet attempts to make a more formal definition of item \"Categories\", as defined by DestinyItemCategoryDefinition. This is a list of all Categories that we were able to algorithmically determine that this item is a member of. (for instance, that it's a \"Weapon\", that it's an \"Auto Rifle\", etc...)  The algorithm for these is, unfortunately, volatile. If you believe you see a miscategorized item, please let us know on the Bungie API forums.
	ItemCategoryHashes []int32 `json:"itemCategoryHashes,omitempty"`
	// In Destiny 1, we identified some items as having particular categories that we'd like to know about for various internal logic purposes. These are defined in SpecialItemType, and while these days the itemCategoryHashes are the preferred way of identifying types, we have retained this enum for its convenience.
	SpecialItemType *interface{} `json:"specialItemType,omitempty"`
	// A value indicating the \"base\" the of the item. This enum is a useful but dramatic oversimplification of what it means for an item to have a \"Type\". Still, it's handy in many situations.  itemCategoryHashes are the preferred way of identifying types, we have retained this enum for its convenience.
	ItemType *interface{} `json:"itemType,omitempty"`
	// A value indicating the \"sub-type\" of the item. For instance, where an item might have an itemType value \"Weapon\", this will be something more specific like \"Auto Rifle\".  itemCategoryHashes are the preferred way of identifying types, we have retained this enum for its convenience.
	ItemSubType *interface{} `json:"itemSubType,omitempty"`
	// We run a similarly weak-sauce algorithm to try and determine whether an item is restricted to a specific class. If we find it to be restricted in such a way, we set this classType property to match the class' enumeration value so that users can easily identify class restricted items.  If you see a mis-classed item, please inform the developers in the Bungie API forum.
	ClassType *interface{} `json:"classType,omitempty"`
	// If true, then you will be allowed to equip the item if you pass its other requirements.  This being false means that you cannot equip the item under any circumstances.
	Equippable bool `json:"equippable,omitempty"`
	// Theoretically, an item can have many possible damage types. In *practice*, this is not true, but just in case weapons start being made that have multiple (for instance, an item where a socket has reusable plugs for every possible damage type that you can choose from freely), this field will return all of the possible damage types that are available to the weapon by default.
	DamageTypeHashes []uint32 `json:"damageTypeHashes,omitempty"`
	// This is the list of all damage types that we know ahead of time the item can take on. Unfortunately, this does not preclude the possibility of something funky happening to give the item a damage type that cannot be predicted beforehand: for example, if some designer decides to create arbitrary non-reusable plugs that cause damage type to change.  This damage type prediction will only use the following to determine potential damage types:  - Intrinsic perks  - Talent Node perks  - Known, reusable plugs for sockets
	DamageTypes []DestinyDamageType `json:"damageTypes,omitempty"`
	// If the item has a damage type that could be considered to be default, it will be populated here.  For various upsetting reasons, it's surprisingly cumbersome to figure this out. I hope you're happy.
	DefaultDamageType *interface{} `json:"defaultDamageType,omitempty"`
	// Similar to defaultDamageType, but represented as the hash identifier for a DestinyDamageTypeDefinition.  I will likely regret leaving in the enumeration versions of these properties, but for now they're very convenient.
	DefaultDamageTypeHash uint32 `json:"defaultDamageTypeHash,omitempty"`
	// The unique identifier for this entity. Guaranteed to be unique for the type of entity, but not globally.  When entities refer to each other in Destiny content, it is this hash that they are referring to.
	Hash uint32 `json:"hash,omitempty"`
	// The index of the entity as it was found in the investment tables.
	Index int32 `json:"index,omitempty"`
	// If this is true, then there is an entity with this identifier/type combination, but BNet is not yet allowed to show it. Sorry!
	Redacted bool `json:"redacted,omitempty"`
}

