/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package api




type DestinyDefinitionsDestinyTalentNodeStepLightAbilities int32

// Enum DestinyDefinitionsDestinyTalentNodeStepLightAbilities
const (
	DestinyDefinitionsDestinyTalentNodeStepLightAbilities_0 DestinyDefinitionsDestinyTalentNodeStepLightAbilities = 0
	DestinyDefinitionsDestinyTalentNodeStepLightAbilities_1 DestinyDefinitionsDestinyTalentNodeStepLightAbilities = 1
	DestinyDefinitionsDestinyTalentNodeStepLightAbilities_2 DestinyDefinitionsDestinyTalentNodeStepLightAbilities = 2
	DestinyDefinitionsDestinyTalentNodeStepLightAbilities_4 DestinyDefinitionsDestinyTalentNodeStepLightAbilities = 4
	DestinyDefinitionsDestinyTalentNodeStepLightAbilities_8 DestinyDefinitionsDestinyTalentNodeStepLightAbilities = 8
	DestinyDefinitionsDestinyTalentNodeStepLightAbilities_16 DestinyDefinitionsDestinyTalentNodeStepLightAbilities = 16
	DestinyDefinitionsDestinyTalentNodeStepLightAbilities_32 DestinyDefinitionsDestinyTalentNodeStepLightAbilities = 32
	DestinyDefinitionsDestinyTalentNodeStepLightAbilities_63 DestinyDefinitionsDestinyTalentNodeStepLightAbilities = 63
)


