/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package api




// Properties of a DestinyInventoryItemDefinition that store all of the information we were able to discern about how the item spawns, and where you can find the item.  Items will have many of these sources, one per level at which it spawns, to try and give more granular data about where items spawn for specific level ranges.
type DestinyDefinitionsSourcesDestinyItemSourceDefinition struct {
	// The level at which the item spawns. Essentially the Primary Key for this source data: there will be multiple of these source entries per item that has source data, grouped by the level at which the item spawns.
	Level int32 `json:"level,omitempty"`
	// The minimum Quality at which the item spawns for this level. Examine DestinyInventoryItemDefinition for more information about what Quality means. Just don't ask Phaedrus about it, he'll never stop talking and you'll have to write a book about it.
	MinQuality int32 `json:"minQuality,omitempty"`
	// The maximum quality at which the item spawns for this level.
	MaxQuality int32 `json:"maxQuality,omitempty"`
	// The minimum Character Level required for equipping the item when the item spawns at the item level defined on this DestinyItemSourceDefinition, as far as we saw in our processing.
	MinLevelRequired int32 `json:"minLevelRequired,omitempty"`
	// The maximum Character Level required for equipping the item when the item spawns at the item level defined on this DestinyItemSourceDefinition, as far as we saw in our processing.
	MaxLevelRequired int32 `json:"maxLevelRequired,omitempty"`
	// The stats computed for this level/quality range.
	ComputedStats map[string]DestinyDefinitionsDestinyInventoryItemStatDefinition `json:"computedStats,omitempty"`
	// The DestinyRewardSourceDefinitions found that can spawn the item at this level.
	SourceHashes []int32 `json:"sourceHashes,omitempty"`
}

