/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package api




// Represents the \"Live\" data that we can obtain about a Character's status with a specific Activity. This will tell you whether the character can participate in the activity, as well as some other basic mutable information.   Meant to be combined with static DestinyActivityDefinition data for a full picture of the Activity.
type DestinyDestinyActivity struct {
	// The hash identifier of the Activity. Use this to look up the DestinyActivityDefinition of the activity.
	ActivityHash int32 `json:"activityHash,omitempty"`
	// If true, then the activity should have a \"new\" indicator in the Director UI.
	IsNew bool `json:"isNew,omitempty"`
	// If true, the user is allowed to lead a Fireteam into this activity.
	CanLead bool `json:"canLead,omitempty"`
	// If true, the user is allowed to join with another Fireteam in this activity.
	CanJoin bool `json:"canJoin,omitempty"`
	// If true, we both have the ability to know that the user has completed this activity and they have completed it. Unfortunately, we can't necessarily know this for all activities. As such, this should probably only be used if you already know in advance which specific activities you wish to check.
	IsCompleted bool `json:"isCompleted,omitempty"`
	// If true, the user should be able to see this activity.
	IsVisible bool `json:"isVisible,omitempty"`
	// The difficulty level of the activity, if applicable.
	DisplayLevel int32 `json:"displayLevel,omitempty"`
	// The recommended light level for the activity, if applicable.
	RecommendedLight int32 `json:"recommendedLight,omitempty"`
	// A DestinyActivityDifficultyTier enum value indicating the difficulty of the activity.
	DifficultyTier *interface{} `json:"difficultyTier,omitempty"`
}

