/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package api





type DestinyHistoricalStatsDestinyHistoricalStatsActivity struct {
	// Hash ID that can be looked up in the DestinyActivityTable.
	ReferenceId int32 `json:"referenceId,omitempty"`
	
	DirectorActivityHash int32 `json:"directorActivityHash,omitempty"`
	// This value can be used to get additional data about this activity such as who else was playing.
	InstanceId int64 `json:"instanceId,omitempty"`
	// Indicates the game mode of the activity.
	Mode *interface{} `json:"mode,omitempty"`
	
	Modes []DestinyHistoricalStatsDefinitionsDestinyActivityModeType `json:"modes,omitempty"`
	// Whether or not the match was a private match.
	IsPrivate bool `json:"isPrivate,omitempty"`
}

