/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package api




// Information about a single inventory bucket in a vendor flyout UI and how it is shown.
type DestinyDefinitionsDestinyVendorInventoryFlyoutBucketDefinition struct {
	// If true, the inventory bucket should be able to be collapsed visually.
	Collapsible bool `json:"collapsible,omitempty"`
	// The inventory bucket whose contents should be shown.
	InventoryBucketHash int32 `json:"inventoryBucketHash,omitempty"`
	// The methodology to use for sorting items from the flyout.
	SortItemsBy *interface{} `json:"sortItemsBy,omitempty"`
}

