/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package api




// This describes links between the current graph and others, as well as when that link is relevant.
type DestinyDefinitionsDirectorDestinyLinkedGraphDefinition struct {
	
	Description string `json:"description,omitempty"`
	
	Name string `json:"name,omitempty"`
	
	UnlockExpression *DestinyDefinitionsDestinyUnlockExpressionDefinition `json:"unlockExpression,omitempty"`
	
	LinkedGraphId int32 `json:"linkedGraphId,omitempty"`
	
	LinkedGraphs []DestinyDefinitionsDirectorDestinyLinkedGraphEntryDefinition `json:"linkedGraphs,omitempty"`
	
	Overview string `json:"overview,omitempty"`
}

