/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package api




type DestinyDamageType int32

// Enum DestinyDamageType
const (
	DestinyDamageType_0 DestinyDamageType = 0
	DestinyDamageType_1 DestinyDamageType = 1
	DestinyDamageType_2 DestinyDamageType = 2
	DestinyDamageType_3 DestinyDamageType = 3
	DestinyDamageType_4 DestinyDamageType = 4
	DestinyDamageType_5 DestinyDamageType = 5
)


