/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package api




// The localized properties of the requirementsDisplay, allowing information about the requirement or item being featured to be seen.
type DestinyDefinitionsDestinyVendorRequirementDisplayEntryDefinition struct {
	
	Icon string `json:"icon,omitempty"`
	
	Name string `json:"name,omitempty"`
	
	Source string `json:"source,omitempty"`
	
	Type_ string `json:"type,omitempty"`
}

