/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package api




// The definition information for a specific socket on an item. This will determine how the socket behaves in-game.
type DestinyDefinitionsDestinyItemSocketEntryDefinition struct {
	// All sockets have a type, and this is the hash identifier for this particular type. Use it to look up the DestinySocketTypeDefinition: read there for more information on how socket types affect the behavior of the socket.
	SocketTypeHash int32 `json:"socketTypeHash,omitempty"`
	// If a valid hash, this is the hash identifier for the DestinyInventoryItemDefinition representing the Plug that will be initially inserted into the item on item creation. Otherwise, this Socket will either start without a plug inserted, or will have one randomly inserted.
	SingleInitialItemHash int32 `json:"singleInitialItemHash,omitempty"`
	// This is a list of pre-determined plugs that can *always* be plugged into this socket, without the character having the plug in their inventory.  If this list is populated, you will not be allowed to plug an arbitrary item in the socket: you will only be able to choose from one of these reusable plugs.
	ReusablePlugItems []DestinyDefinitionsDestinyItemSocketEntryPlugItemDefinition `json:"reusablePlugItems,omitempty"`
}

