/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package api



// DestinyDestinyVendorReplyType : This determines the type of reply that a Vendor will have during an Interaction.
type DestinyDestinyVendorReplyType int32

// Enum DestinyDestinyVendorReplyType
const (
	DestinyDestinyVendorReplyType_0 DestinyDestinyVendorReplyType = 0
	DestinyDestinyVendorReplyType_1 DestinyDestinyVendorReplyType = 1
	DestinyDestinyVendorReplyType_2 DestinyDestinyVendorReplyType = 2
)


