/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package api





type DestinyComponentsKiosksDestinyKioskItem struct {
	// The index of the item in the related DestinyVendorDefintion's itemList property, representing the sale.
	Index int32 `json:"index,omitempty"`
	// If true, the user can not only see the item, but they can acquire it. It is possible that a user can see a kiosk item and not be able to acquire it.
	CanAcquire bool `json:"canAcquire,omitempty"`
	// Indexes into failureStrings for the Vendor, indicating the reasons why it failed if any.
	FailureIndexes []int32 `json:"failureIndexes,omitempty"`
}

