/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package api




// Sockets are grouped into categories in the UI. These define which category and which sockets are under that category.
type DestinyDefinitionsDestinyItemSocketCategoryDefinition struct {
	// The hash for the Socket Category: a quick way to go get the header display information for the category. Use it to look up DestinySocketCategoryDefinition info.
	SocketCategoryHash int32 `json:"socketCategoryHash,omitempty"`
	// Use these indexes to look up the sockets in the \"sockets.socketEntries\" property on the item definition. These are the indexes under the category, in game-rendered order.
	SocketIndexes []int32 `json:"socketIndexes,omitempty"`
}

