/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package api



// DestinySpecialItemType : As you run into items that need to be classified for Milestone purposes in ways that we cannot infer via Babel or Bonbobo-sourced data, add a new classification here and use a string constant to represent it in the local item config file.  NOTE: This is not all of the item types available, and some of these are holdovers from Destiny 1 that may or may not still exist.
type DestinySpecialItemType int32

// Enum DestinySpecialItemType
const (
	DestinySpecialItemType_0 DestinySpecialItemType = 0
	DestinySpecialItemType_1 DestinySpecialItemType = 1
	DestinySpecialItemType_8 DestinySpecialItemType = 8
	DestinySpecialItemType_9 DestinySpecialItemType = 9
	DestinySpecialItemType_23 DestinySpecialItemType = 23
	DestinySpecialItemType_24 DestinySpecialItemType = 24
	DestinySpecialItemType_25 DestinySpecialItemType = 25
	DestinySpecialItemType_27 DestinySpecialItemType = 27
	DestinySpecialItemType_29 DestinySpecialItemType = 29
)


