/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package api





type DestinyDefinitionsDestinyVendorDisplayPropertiesDefinition struct {
	
	LargeIcon string `json:"largeIcon,omitempty"`
	
	Subtitle string `json:"subtitle,omitempty"`
	// Vendors, in addition to expected display property data, may also show some \"common requirements\" as statically defined definition data. This might be when a vendor accepts a single type of currency, or when the currency is unique to the vendor and the designers wanted to show that currency when you interact with the vendor.
	RequirementsDisplay []DestinyDefinitionsDestinyVendorRequirementDisplayEntryDefinition `json:"requirementsDisplay,omitempty"`
	
	Description string `json:"description,omitempty"`
	
	Name string `json:"name,omitempty"`
	// Note that \"icon\" is sometimes misleading, and should be interpreted in the context of the entity. For instance, in Destiny 1 the DestinyRecordBookDefinition's icon was a big picture of a book.  But usually, it will be a small square image that you can use as... well, an icon.
	Icon string `json:"icon,omitempty"`
	
	HasIcon bool `json:"hasIcon,omitempty"`
}

