/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package api



// DestinyDestinyItemSortType : Determines how items are sorted in an inventory bucket.
type DestinyDestinyItemSortType int32

// Enum DestinyDestinyItemSortType
const (
	DestinyDestinyItemSortType_0 DestinyDestinyItemSortType = 0
	DestinyDestinyItemSortType_1 DestinyDestinyItemSortType = 1
	DestinyDestinyItemSortType_2 DestinyDestinyItemSortType = 2
)


