/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package api

import (
	"time"
)



// Information about milestones, presented in a character state-agnostic manner. Combine this data with DestinyMilestoneDefinition to get a full picture of the milestone, which is basically a checklist of things to do in the game. Think of this as GetPublicAdvisors 3.0, for those who used the Destiny 1 API.
type DestinyMilestonesDestinyPublicMilestone struct {
	// The hash identifier for the milestone. Use it to look up the DestinyMilestoneDefinition for static data about the Milestone.
	MilestoneHash int32 `json:"milestoneHash,omitempty"`
	// A milestone not need have even a single quest, but if there are active quests they will be returned here.
	AvailableQuests []DestinyMilestonesDestinyPublicMilestoneQuest `json:"availableQuests,omitempty"`
	// Sometimes milestones - or activities active in milestones - will have relevant vendors. These are the vendors that are currently relevant.
	VendorHashes []int32 `json:"vendorHashes,omitempty"`
	// If known, this is the date when the Milestone started/became active.
	StartDate time.Time `json:"startDate,omitempty"`
	// If known, this is the date when the Milestone will expire/recycle/end.
	EndDate time.Time `json:"endDate,omitempty"`
}

