/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package api



// DestinyDefinitionsMilestonesDestinyMilestoneType : The type of milestone. Milestones can be Tutorials, one-time/triggered/non-repeating but not necessarily tutorials, or Repeating Milestones.
type DestinyDefinitionsMilestonesDestinyMilestoneType int32

// Enum DestinyDefinitionsMilestonesDestinyMilestoneType
const (
	DestinyDefinitionsMilestonesDestinyMilestoneType_0 DestinyDefinitionsMilestonesDestinyMilestoneType = 0
	DestinyDefinitionsMilestonesDestinyMilestoneType_1 DestinyDefinitionsMilestonesDestinyMilestoneType = 1
	DestinyDefinitionsMilestonesDestinyMilestoneType_2 DestinyDefinitionsMilestonesDestinyMilestoneType = 2
	DestinyDefinitionsMilestonesDestinyMilestoneType_3 DestinyDefinitionsMilestonesDestinyMilestoneType = 3
	DestinyDefinitionsMilestonesDestinyMilestoneType_4 DestinyDefinitionsMilestonesDestinyMilestoneType = 4
	DestinyDefinitionsMilestonesDestinyMilestoneType_5 DestinyDefinitionsMilestonesDestinyMilestoneType = 5
)


