/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package api




// The list of perks to display in an item tooltip - and whether or not they have been activated.  Perks apply a variety of effects to a character, and are generally either intrinsic to the item or provided in activated talent nodes or sockets.
type DestinyPerksDestinyPerkReference struct {
	// The hash identifier for the perk, which can be used to look up DestinySandboxPerkDefinition if it exists. Be warned, perks frequently do not have user-viewable information. You should examine whether you actually found a name/description in the perk's definition before you show it to the user.
	PerkHash int32 `json:"perkHash,omitempty"`
	// The icon for the perk.
	IconPath string `json:"iconPath,omitempty"`
	// Whether this perk is currently active. (We may return perks that you have not actually activated yet: these represent perks that you should show in the item's tooltip, but that the user has not yet activated.)
	IsActive bool `json:"isActive,omitempty"`
	// Some perks provide benefits, but aren't visible in the UI. This value will let you know if this is perk should be shown in your UI.
	Visible bool `json:"visible,omitempty"`
}

