/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package api




// Items can have objectives and progression. When you request this block, you will obtain information about any Objectives and progression tied to this item.
type DestinyEntitiesItemsDestinyItemObjectivesComponent struct {
	// If the item has a hard association with objectives, your progress on them will be defined here.   Objectives are our standard way to describe a series of tasks that have to be completed for a reward.
	Objectives []DestinyQuestsDestinyObjectiveProgress `json:"objectives,omitempty"`
}

