/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package api




// Raw data about the customization options chosen for a character's face and appearance.  You can look up the relevant class/race/gender combo in DestinyCharacterCustomizationOptionDefinition for the character, and then look up these values within the CustomizationOptions found to pull some data about their choices. Warning: not all of that data is meaningful. Some data has useful icons. Others have nothing, and are only meant for 3D rendering purposes (which we sadly do not expose yet)
type DestinyCharacterDestinyCharacterCustomization struct {
	
	Personality int32 `json:"personality,omitempty"`
	
	Face int32 `json:"face,omitempty"`
	
	SkinColor int32 `json:"skinColor,omitempty"`
	
	LipColor int32 `json:"lipColor,omitempty"`
	
	EyeColor int32 `json:"eyeColor,omitempty"`
	
	HairColors []int32 `json:"hairColors,omitempty"`
	
	FeatureColors []int32 `json:"featureColors,omitempty"`
	
	DecalColor int32 `json:"decalColor,omitempty"`
	
	WearHelmet bool `json:"wearHelmet,omitempty"`
	
	HairIndex int32 `json:"hairIndex,omitempty"`
	
	FeatureIndex int32 `json:"featureIndex,omitempty"`
	
	DecalIndex int32 `json:"decalIndex,omitempty"`
}

