/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package api

import (
	"time"
)



// This component contains base properties of the character. You'll probably want to always request this component, but hey you do you.
type DestinyEntitiesCharactersDestinyCharacterComponent struct {
	// Every Destiny Profile has a membershipId. This is provided on the character as well for convenience.
	MembershipId int64 `json:"membershipId,omitempty"`
	// membershipType tells you the platform on which the character plays. Examine the BungieMembershipType enumeration for possible values.
	MembershipType *interface{} `json:"membershipType,omitempty"`
	// The unique identifier for the character.
	CharacterId int64 `json:"characterId,omitempty"`
	// The last date that the user played Destiny.
	DateLastPlayed time.Time `json:"dateLastPlayed,omitempty"`
	// If the user is currently playing, this is how long they've been playing.
	MinutesPlayedThisSession int64 `json:"minutesPlayedThisSession,omitempty"`
	// If this value is 525,600, then they played Destiny for a year. Or they're a very dedicated Rent fan. Note that this includes idle time, not just time spent actually in activities shooting things.
	MinutesPlayedTotal int64 `json:"minutesPlayedTotal,omitempty"`
	// The user's calculated \"Light Level\". Light level is an indicator of your power that mostly matters in the end game, once you've reached the maximum character level: it's a level that's dependent on the average Attack/Defense power of your items.
	Light int32 `json:"light,omitempty"`
	// Your character's stats, such as Agility, Resilience, etc... *not* historical stats.  You'll have to call a different endpoint for those.
	Stats map[string]int32 `json:"stats,omitempty"`
	// Use this hash to look up the character's DestinyRaceDefinition.
	RaceHash int32 `json:"raceHash,omitempty"`
	// Use this hash to look up the character's DestinyGenderDefinition.
	GenderHash int32 `json:"genderHash,omitempty"`
	// Use this hash to look up the character's DestinyClassDefinition.
	ClassHash int32 `json:"classHash,omitempty"`
	// Mostly for historical purposes at this point, this is an enumeration for the character's race.  It'll be preferable in the general case to look up the related definition: but for some people this was too convenient to remove.
	RaceType *interface{} `json:"raceType,omitempty"`
	// Mostly for historical purposes at this point, this is an enumeration for the character's class.  It'll be preferable in the general case to look up the related definition: but for some people this was too convenient to remove.
	ClassType *interface{} `json:"classType,omitempty"`
	// Mostly for historical purposes at this point, this is an enumeration for the character's Gender.  It'll be preferable in the general case to look up the related definition: but for some people this was too convenient to remove. And yeah, it's an enumeration and not a boolean. Fight me.
	GenderType *interface{} `json:"genderType,omitempty"`
	// A shortcut path to the user's currently equipped emblem image. If you're just showing summary info for a user, this is more convenient than examining their equipped emblem and looking up the definition.
	EmblemPath string `json:"emblemPath,omitempty"`
	// A shortcut path to the user's currently equipped emblem background image. If you're just showing summary info for a user, this is more convenient than examining their equipped emblem and looking up the definition.
	EmblemBackgroundPath string `json:"emblemBackgroundPath,omitempty"`
	// The hash of the currently equipped emblem for the user. Can be used to look up the DestinyInventoryItemDefinition.
	EmblemHash int32 `json:"emblemHash,omitempty"`
	// The progression that indicates your character's level. Not their light level, but their character level: you know, the thing you max out a couple hours in and then ignore for the sake of light level.
	LevelProgression *interface{} `json:"levelProgression,omitempty"`
	// The \"base\" level of your character, not accounting for any light level.
	BaseCharacterLevel int32 `json:"baseCharacterLevel,omitempty"`
	// A number between 0 and 100, indicating the whole and fractional % remaining to get to the next character level.
	PercentToNextLevel float32 `json:"percentToNextLevel,omitempty"`
}

