/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package api




// If a vendor can ever end up performing actions, these are the properties that will be related to those actions. I'm not going to bother documenting this yet, as it is unused and unclear if it will ever be used... but in case it is ever populated and someone finds it useful, it is defined here.
type DestinyDefinitionsDestinyVendorActionDefinition struct {
	
	Description string `json:"description,omitempty"`
	
	ExecuteSeconds int32 `json:"executeSeconds,omitempty"`
	
	Icon string `json:"icon,omitempty"`
	
	Name string `json:"name,omitempty"`
	
	Verb string `json:"verb,omitempty"`
	
	IsPositive bool `json:"isPositive,omitempty"`
	
	ActionId string `json:"actionId,omitempty"`
	
	ActionHash int32 `json:"actionHash,omitempty"`
	
	AutoPerformAction bool `json:"autoPerformAction,omitempty"`
}

