/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package api




// All damage types that are possible in the game are defined here, along with localized info and icons as needed.
type DestinyDefinitionsDestinyDamageTypeDefinition struct {
	// The description of the damage type, icon etc...
	DisplayProperties *interface{} `json:"displayProperties,omitempty"`
	// A variant of the icon that is transparent and colorless.
	TransparentIconPath string `json:"transparentIconPath,omitempty"`
	// If TRUE, the game shows this damage type's icon. Otherwise, it doesn't. Whether you show it or not is up to you.
	ShowIcon bool `json:"showIcon,omitempty"`
	// We have an enumeration for damage types for quick reference. This is the current definition's damage type enum value.
	EnumValue *interface{} `json:"enumValue,omitempty"`
	// The unique identifier for this entity. Guaranteed to be unique for the type of entity, but not globally.  When entities refer to each other in Destiny content, it is this hash that they are referring to.
	Hash int32 `json:"hash,omitempty"`
	// The index of the entity as it was found in the investment tables.
	Index int32 `json:"index,omitempty"`
	// If this is true, then there is an entity with this identifier/type combination, but BNet is not yet allowed to show it. Sorry!
	Redacted bool `json:"redacted,omitempty"`
}

