/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package api



// DestinyDestinyItemSubType : This Enumeration further classifies items by more specific categorizations than DestinyItemType. The \"Sub-Type\" is where we classify and categorize items one step further in specificity: \"Auto Rifle\" instead of just \"Weapon\" for example, or \"Vanguard Bounty\" instead of merely \"Bounty\".  These sub-types are provided for historical compatibility with Destiny 1, but an ideal alternative is to use DestinyItemCategoryDefinitions and the DestinyItemDefinition.itemCategories property instead. Item Categories allow for arbitrary hierarchies of specificity, and for items to belong to multiple categories across multiple hierarchies simultaneously. For this enum, we pick a single type as a \"best guess\" fit.  NOTE: This is not all of the item types available, and some of these are holdovers from Destiny 1 that may or may not still exist.
type DestinyDestinyItemSubType int32

// Enum DestinyDestinyItemSubType
const (
	DestinyDestinyItemSubType_0 DestinyDestinyItemSubType = 0
	DestinyDestinyItemSubType_1 DestinyDestinyItemSubType = 1
	DestinyDestinyItemSubType_2 DestinyDestinyItemSubType = 2
	DestinyDestinyItemSubType_5 DestinyDestinyItemSubType = 5
	DestinyDestinyItemSubType_6 DestinyDestinyItemSubType = 6
	DestinyDestinyItemSubType_7 DestinyDestinyItemSubType = 7
	DestinyDestinyItemSubType_8 DestinyDestinyItemSubType = 8
	DestinyDestinyItemSubType_9 DestinyDestinyItemSubType = 9
	DestinyDestinyItemSubType_10 DestinyDestinyItemSubType = 10
	DestinyDestinyItemSubType_11 DestinyDestinyItemSubType = 11
	DestinyDestinyItemSubType_12 DestinyDestinyItemSubType = 12
	DestinyDestinyItemSubType_13 DestinyDestinyItemSubType = 13
	DestinyDestinyItemSubType_14 DestinyDestinyItemSubType = 14
	DestinyDestinyItemSubType_16 DestinyDestinyItemSubType = 16
	DestinyDestinyItemSubType_17 DestinyDestinyItemSubType = 17
	DestinyDestinyItemSubType_18 DestinyDestinyItemSubType = 18
	DestinyDestinyItemSubType_19 DestinyDestinyItemSubType = 19
	DestinyDestinyItemSubType_20 DestinyDestinyItemSubType = 20
)


