/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package api



// DestinyEquipFailureReason : The reasons why an item cannot be equipped, if any. Many flags can be set, or \"None\" if
type DestinyEquipFailureReason int32

// Enum DestinyEquipFailureReason
const (
	DestinyEquipFailureReason_0 DestinyEquipFailureReason = 0
	DestinyEquipFailureReason_1 DestinyEquipFailureReason = 1
	DestinyEquipFailureReason_2 DestinyEquipFailureReason = 2
	DestinyEquipFailureReason_4 DestinyEquipFailureReason = 4
	DestinyEquipFailureReason_8 DestinyEquipFailureReason = 8
	DestinyEquipFailureReason_16 DestinyEquipFailureReason = 16
)


