/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package api




type DestinyDestinyComponentType int32

// Enum DestinyDestinyComponentType
const (
	DestinyDestinyComponentType_0 DestinyDestinyComponentType = 0
	DestinyDestinyComponentType_100 DestinyDestinyComponentType = 100
	DestinyDestinyComponentType_101 DestinyDestinyComponentType = 101
	DestinyDestinyComponentType_102 DestinyDestinyComponentType = 102
	DestinyDestinyComponentType_103 DestinyDestinyComponentType = 103
	DestinyDestinyComponentType_200 DestinyDestinyComponentType = 200
	DestinyDestinyComponentType_201 DestinyDestinyComponentType = 201
	DestinyDestinyComponentType_202 DestinyDestinyComponentType = 202
	DestinyDestinyComponentType_203 DestinyDestinyComponentType = 203
	DestinyDestinyComponentType_204 DestinyDestinyComponentType = 204
	DestinyDestinyComponentType_205 DestinyDestinyComponentType = 205
	DestinyDestinyComponentType_300 DestinyDestinyComponentType = 300
	DestinyDestinyComponentType_301 DestinyDestinyComponentType = 301
	DestinyDestinyComponentType_302 DestinyDestinyComponentType = 302
	DestinyDestinyComponentType_303 DestinyDestinyComponentType = 303
	DestinyDestinyComponentType_304 DestinyDestinyComponentType = 304
	DestinyDestinyComponentType_305 DestinyDestinyComponentType = 305
	DestinyDestinyComponentType_306 DestinyDestinyComponentType = 306
	DestinyDestinyComponentType_307 DestinyDestinyComponentType = 307
	DestinyDestinyComponentType_308 DestinyDestinyComponentType = 308
	DestinyDestinyComponentType_400 DestinyDestinyComponentType = 400
	DestinyDestinyComponentType_401 DestinyDestinyComponentType = 401
	DestinyDestinyComponentType_402 DestinyDestinyComponentType = 402
	DestinyDestinyComponentType_500 DestinyDestinyComponentType = 500
)


