/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package api




// Nodes on a graph can be visually connected: this appears to be the information about which nodes to link. It appears to lack more detailed information, such as the path for that linking.
type DestinyDefinitionsDirectorDestinyActivityGraphConnectionDefinition struct {
	
	SourceNodeHash int32 `json:"sourceNodeHash,omitempty"`
	
	DestNodeHash int32 `json:"destNodeHash,omitempty"`
}

