/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package api




// As of Destiny 2, nodes can exist as part of \"Exclusive Groups\". These differ from exclusive sets in that, within the group, many nodes can be activated. But the act of activating any node in the group will cause \"opposing\" nodes (nodes in groups that are not allowed to be activated at the same time as this group) to deactivate.
type DestinyDefinitionsDestinyTalentExclusiveGroup struct {
	// The identifier for this exclusive group. Only guaranteed unique within the talent grid, not globally.
	GroupHash int32 `json:"groupHash,omitempty"`
	// If this group has an associated piece of lore to show next to it, this will be the identifier for that DestinyLoreDefinition.
	LoreHash int32 `json:"loreHash,omitempty"`
	// A quick reference of the talent nodes that are part of this group, by their Talent Node hashes. (See DestinyTalentNodeDefinition.nodeHash)
	NodeHashes []int32 `json:"nodeHashes,omitempty"`
	// A quick reference of Groups whose nodes will be deactivated if any node in this group is activated.
	OpposingGroupHashes []int32 `json:"opposingGroupHashes,omitempty"`
	// A quick reference of Nodes that will be deactivated if any node in this group is activated, by their Talent Node hashes. (See DestinyTalentNodeDefinition.nodeHash)
	OpposingNodeHashes []int32 `json:"opposingNodeHashes,omitempty"`
}

