/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package api




// An overly complicated wrapper for the item level at which the item should spawn.
type DestinyDefinitionsDestinyItemCreationEntryLevelDefinition struct {
	
	Level int32 `json:"level,omitempty"`
}

