/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package api





type DestinyItemComponentSetOfint32 struct {
	
	Instances *DictionaryComponentResponseOfint32AndDestinyItemInstanceComponent `json:"instances,omitempty"`
	
	Objectives *DictionaryComponentResponseOfint32AndDestinyItemObjectivesComponent `json:"objectives,omitempty"`
	
	Perks *DictionaryComponentResponseOfint32AndDestinyItemPerksComponent `json:"perks,omitempty"`
	
	RenderData *DictionaryComponentResponseOfint32AndDestinyItemRenderComponent `json:"renderData,omitempty"`
	
	Stats *DictionaryComponentResponseOfint32AndDestinyItemStatsComponent `json:"stats,omitempty"`
	
	Sockets *DictionaryComponentResponseOfint32AndDestinyItemSocketsComponent `json:"sockets,omitempty"`
	
	TalentGrids *DictionaryComponentResponseOfint32AndDestinyItemTalentGridComponent `json:"talentGrids,omitempty"`
	
	PlugStates *DictionaryComponentResponseOfuint32AndDestinyItemPlugComponent `json:"plugStates,omitempty"`
}

