/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package api




type DestinyItemState int32

// Enum DestinyItemState
const (
	DestinyItemState_0 DestinyItemState = 0
	DestinyItemState_1 DestinyItemState = 1
	DestinyItemState_2 DestinyItemState = 2
)


