/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package api



// DestinyDestinyUnlockValueUiStyle : If you're showing an unlock value in the UI, this is the format in which it should be shown. You'll have to build your own algorithms on the client side to determine how best to render these options.
type DestinyDestinyUnlockValueUiStyle int32

// Enum DestinyDestinyUnlockValueUiStyle
const (
	DestinyDestinyUnlockValueUiStyle_0 DestinyDestinyUnlockValueUiStyle = 0
	DestinyDestinyUnlockValueUiStyle_1 DestinyDestinyUnlockValueUiStyle = 1
	DestinyDestinyUnlockValueUiStyle_2 DestinyDestinyUnlockValueUiStyle = 2
	DestinyDestinyUnlockValueUiStyle_3 DestinyDestinyUnlockValueUiStyle = 3
	DestinyDestinyUnlockValueUiStyle_4 DestinyDestinyUnlockValueUiStyle = 4
	DestinyDestinyUnlockValueUiStyle_5 DestinyDestinyUnlockValueUiStyle = 5
	DestinyDestinyUnlockValueUiStyle_6 DestinyDestinyUnlockValueUiStyle = 6
	DestinyDestinyUnlockValueUiStyle_7 DestinyDestinyUnlockValueUiStyle = 7
	DestinyDestinyUnlockValueUiStyle_8 DestinyDestinyUnlockValueUiStyle = 8
)


