/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package api




// Bare minimum summary information for an item, for the sake of 3D rendering the item.
type DestinyCharacterDestinyItemPeerView struct {
	// The hash identifier of the item in question. Use it to look up the DestinyInventoryItemDefinition of the item for static rendering data.
	ItemHash int32 `json:"itemHash,omitempty"`
	// The list of dyes that have been applied to this item.
	Dyes []DestinyDyeReference `json:"dyes,omitempty"`
}

