/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package api




// These properties are an attempt to categorize talent node steps by certain common properties. See the related enumerations for the type of properties being categorized.
type DestinyDefinitionsDestinyTalentNodeStepGroups struct {
	
	WeaponPerformance *DestinyDefinitionsDestinyTalentNodeStepWeaponPerformances `json:"weaponPerformance,omitempty"`
	
	ImpactEffects *DestinyDefinitionsDestinyTalentNodeStepImpactEffects `json:"impactEffects,omitempty"`
	
	GuardianAttributes *DestinyDefinitionsDestinyTalentNodeStepGuardianAttributes `json:"guardianAttributes,omitempty"`
	
	LightAbilities *DestinyDefinitionsDestinyTalentNodeStepLightAbilities `json:"lightAbilities,omitempty"`
	
	DamageTypes *DestinyDefinitionsDestinyTalentNodeStepDamageTypes `json:"damageTypes,omitempty"`
}

