/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package api




type DestinyBucketCategory int32

// Enum DestinyBucketCategory
const (
	DestinyBucketCategory_0 DestinyBucketCategory = 0
	DestinyBucketCategory_1 DestinyBucketCategory = 1
	DestinyBucketCategory_2 DestinyBucketCategory = 2
	DestinyBucketCategory_3 DestinyBucketCategory = 3
	DestinyBucketCategory_4 DestinyBucketCategory = 4
)


