/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package api




type DestinyHistoricalStatsDefinitionsPeriodType int32

// Enum DestinyHistoricalStatsDefinitionsPeriodType
const (
	DestinyHistoricalStatsDefinitionsPeriodType_0 DestinyHistoricalStatsDefinitionsPeriodType = 0
	DestinyHistoricalStatsDefinitionsPeriodType_1 DestinyHistoricalStatsDefinitionsPeriodType = 1
	DestinyHistoricalStatsDefinitionsPeriodType_2 DestinyHistoricalStatsDefinitionsPeriodType = 2
	DestinyHistoricalStatsDefinitionsPeriodType_3 DestinyHistoricalStatsDefinitionsPeriodType = 3
)


