/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package api




// A Vendor Interaction is a dialog shown by the vendor other than sale items or transfer screens. The vendor is showing you something, and asking you to reply to it by choosing an option or reward.
type DestinyDefinitionsDestinyVendorInteractionDefinition struct {
	// The potential replies that the user can make to the interaction.
	Replies []DestinyDefinitionsDestinyVendorInteractionReplyDefinition `json:"replies,omitempty"`
	// If >= 0, this is the category of sale items to show along with this interaction dialog.
	VendorCategoryIndex int32 `json:"vendorCategoryIndex,omitempty"`
	// If this interaction dialog is about a quest, this is the questline related to the interaction. You can use this to show the quest overview, or even the character's status with the quest if you use it to find the character's current Quest Step by checking their inventory against this questlineItemHash's DestinyInventoryItemDefinition.setData.
	QuestlineItemHash int32 `json:"questlineItemHash,omitempty"`
	// If this interaction is meant to show you sacks, this is the list of types of sacks to be shown. If empty, the interaction is not meant to show sacks.
	SackInteractionList []DestinyDefinitionsDestinyVendorInteractionSackEntryDefinition `json:"sackInteractionList,omitempty"`
	// A UI hint for the behavior of the interaction screen. BNet doesn't use this, but you can choose to.
	UiInteractionType int32 `json:"uiInteractionType,omitempty"`
	// If this interaction is displaying rewards, this is the text to use for the header of the reward-displaying section of the interaction.
	RewardBlockLabel string `json:"rewardBlockLabel,omitempty"`
	// If the vendor's reward list is sourced from one of his categories, this is the index into the category array of items to show.
	RewardVendorCategoryIndex int32 `json:"rewardVendorCategoryIndex,omitempty"`
	// If the vendor interaction has flavor text, this is some of it.
	FlavorLineOne string `json:"flavorLineOne,omitempty"`
	// If the vendor interaction has flavor text, this is the rest of it.
	FlavorLineTwo string `json:"flavorLineTwo,omitempty"`
	// The header for the interaction dialog.
	HeaderDisplayProperties *interface{} `json:"headerDisplayProperties,omitempty"`
	// The localized text telling the player what to do when they see this dialog.
	Instructions string `json:"instructions,omitempty"`
}

