/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package api




type DestinyDestinyTalentNodeState int32

// Enum DestinyDestinyTalentNodeState
const (
	DestinyDestinyTalentNodeState_0 DestinyDestinyTalentNodeState = 0
	DestinyDestinyTalentNodeState_1 DestinyDestinyTalentNodeState = 1
	DestinyDestinyTalentNodeState_2 DestinyDestinyTalentNodeState = 2
	DestinyDestinyTalentNodeState_3 DestinyDestinyTalentNodeState = 3
	DestinyDestinyTalentNodeState_4 DestinyDestinyTalentNodeState = 4
	DestinyDestinyTalentNodeState_5 DestinyDestinyTalentNodeState = 5
	DestinyDestinyTalentNodeState_6 DestinyDestinyTalentNodeState = 6
	DestinyDestinyTalentNodeState_7 DestinyDestinyTalentNodeState = 7
	DestinyDestinyTalentNodeState_8 DestinyDestinyTalentNodeState = 8
	DestinyDestinyTalentNodeState_9 DestinyDestinyTalentNodeState = 9
	DestinyDestinyTalentNodeState_10 DestinyDestinyTalentNodeState = 10
	DestinyDestinyTalentNodeState_11 DestinyDestinyTalentNodeState = 11
	DestinyDestinyTalentNodeState_12 DestinyDestinyTalentNodeState = 12
	DestinyDestinyTalentNodeState_13 DestinyDestinyTalentNodeState = 13
)


