/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package api




// This is the definition for a single Vendor Category, into which Sale Items are grouped.
type DestinyDefinitionsDestinyVendorCategoryEntryDefinition struct {
	// The index of the category in the original category definitions for the vendor.
	CategoryIndex int32 `json:"categoryIndex,omitempty"`
	// The string identifier of the category.
	CategoryId string `json:"categoryId,omitempty"`
	// The hashed identifier for the category. (note that this is NOT pointing to a DestinyVendorCategoryDefinition, it's confusing but this is a sale item category in a vendor, not a categorization of vendors themselves)
	CategoryHash int32 `json:"categoryHash,omitempty"`
	// The amount of items that will be available when this category is shown.
	QuantityAvailable int32 `json:"quantityAvailable,omitempty"`
	// If items aren't up for sale in this category, should we still show them (greyed out)?
	ShowUnavailableItems bool `json:"showUnavailableItems,omitempty"`
	// If you don't have the currency required to buy items from this category, should the items be hidden?
	HideIfNoCurrency bool `json:"hideIfNoCurrency,omitempty"`
	// True if this category doesn't allow purchases.
	HideFromRegularPurchase bool `json:"hideFromRegularPurchase,omitempty"`
	// The localized string for making purchases from this category, if it is different from the vendor's string for purchasing.
	BuyStringOverride string `json:"buyStringOverride,omitempty"`
	// If the category is disabled, this is the localized description to show.
	DisabledDescription string `json:"disabledDescription,omitempty"`
	// The localized title of the category.
	DisplayTitle string `json:"displayTitle,omitempty"`
	// If this category has an overlay prompt that should appear, this contains the details of that prompt.
	Overlay *interface{} `json:"overlay,omitempty"`
}

