/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package api




// The details of an overlay prompt to show to a user. They are all fairly self-explanatory localized strings that can be shown.
type DestinyDefinitionsDestinyVendorCategoryOverlayDefinition struct {
	
	ChoiceDescription string `json:"choiceDescription,omitempty"`
	
	Description string `json:"description,omitempty"`
	
	Icon string `json:"icon,omitempty"`
	
	Title string `json:"title,omitempty"`
}

