/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package api




// Defines the conditions under which an intrinsic perk is applied while participating in an Objective.  These perks will generally not be benefit-granting perks, but rather a perk that modifies gameplay in some interesting way.
type DestinyDefinitionsDestinyObjectivePerkEntryDefinition struct {
	// The hash identifier of the DestinySandboxPerkDefinition that will be applied to the character.
	PerkHash int32 `json:"perkHash,omitempty"`
	// An enumeration indicating whether it will be applied as long as the Objective is active, when it's completed, or until it's completed.
	Style *interface{} `json:"style,omitempty"`
}

