/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package api




type DestinyItemLocation int32

// Enum DestinyItemLocation
const (
	DestinyItemLocation_0 DestinyItemLocation = 0
	DestinyItemLocation_1 DestinyItemLocation = 1
	DestinyItemLocation_2 DestinyItemLocation = 2
	DestinyItemLocation_3 DestinyItemLocation = 3
	DestinyItemLocation_4 DestinyItemLocation = 4
)


