/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package api




// This defines a single Step in a progression (which roughly equates to a level. See DestinyProgressionDefinition for caveats).
type DestinyDefinitionsDestinyProgressionStepDefinition struct {
	// Very rarely, Progressions will have localized text describing the Level of the progression. This will be that localized text, if it exists. Otherwise, the standard appears to be to simply show the level numerically.
	StepName string `json:"stepName,omitempty"`
	// This appears to be, when you \"level up\", whether a visual effect will display and on what entity. See DestinyProgressionStepDisplayEffect for slightly more info.
	DisplayEffectType *interface{} `json:"displayEffectType,omitempty"`
	// The total amount of progression points/\"experience\" you will need to initially reach this step. If this is the last step and the progression is repeating indefinitely (DestinyProgressionDefinition.repeatLastStep), this will also be the progress needed to level it up further by repeating this step again.
	ProgressTotal int32 `json:"progressTotal,omitempty"`
	// A listing of items rewarded as a result of reaching this level.
	RewardItems []DestinyDestinyItemQuantity `json:"rewardItems,omitempty"`
}

