/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package api




// An item can have objectives on it. In practice, these are the exclusive purview of \"Quest Step\" items: DestinyInventoryItemDefinitions that represent a specific step in a Quest.  Quest steps have 1:M objectives that we end up processing and returning in live data as DestinyQuestStatus data, and other useful information.
type DestinyDefinitionsDestinyItemObjectiveBlockDefinition struct {
	// The hashes to Objectives (DestinyObjectiveDefinition) that are part of this Quest Step, in the order that they should be rendered.
	ObjectiveHashes []int32 `json:"objectiveHashes,omitempty"`
	// For every entry in objectiveHashes, there is a corresponding entry in this array at the same index. If the objective is meant to be associated with a specific DestinyActivityDefinition, there will be a valid hash at that index. Otherwise, it will be invalid (0).
	DisplayActivityHashes []int32 `json:"displayActivityHashes,omitempty"`
	// If True, all objectives must be completed for the step to be completed. If False, any one objective can be completed for the step to be completed.
	RequireFullObjectiveCompletion bool `json:"requireFullObjectiveCompletion,omitempty"`
	// The hash for the DestinyInventoryItemDefinition representing the Quest to which this Quest Step belongs.
	QuestlineItemHash int32 `json:"questlineItemHash,omitempty"`
	// The localized string for narrative text related to this quest step, if any.
	Narrative string `json:"narrative,omitempty"`
	// The localized string describing an action to be performed associated with the objectives, if any.
	ObjectiveVerbName string `json:"objectiveVerbName,omitempty"`
	// The identifier for the type of quest being performed, if any. Not associated with any fixed definition, yet.
	QuestTypeIdentifier string `json:"questTypeIdentifier,omitempty"`
	// A hashed value for the questTypeIdentifier, because apparently I like to be redundant.
	QuestTypeHash int32 `json:"questTypeHash,omitempty"`
}

