/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package api





type DestinyDefinitionsDestinyActivityModeDefinition struct {
	
	DisplayProperties *DestinyDefinitionsCommonDestinyDisplayPropertiesDefinition `json:"displayProperties,omitempty"`
	
	PgcrImage string `json:"pgcrImage,omitempty"`
	
	ModeType *DestinyHistoricalStatsDefinitionsDestinyActivityModeType `json:"modeType,omitempty"`
	
	ActivityModeCategory *DestinyDestinyActivityModeCategory `json:"activityModeCategory,omitempty"`
	
	IsTeamBased bool `json:"isTeamBased,omitempty"`
	
	IsAggregateMode bool `json:"isAggregateMode,omitempty"`
	
	ParentHashes []int32 `json:"parentHashes,omitempty"`
	
	FriendlyName string `json:"friendlyName,omitempty"`
	
	ActivityModeMappings map[string]DestinyHistoricalStatsDefinitionsDestinyActivityModeType `json:"activityModeMappings,omitempty"`
	// If FALSE, we want to ignore this type when we're showing activity modes in BNet UI. It will still be returned in case 3rd parties want to use it for any purpose.
	Display bool `json:"display,omitempty"`
	// The relative ordering of activity modes.
	Order int32 `json:"order,omitempty"`
	// The unique identifier for this entity. Guaranteed to be unique for the type of entity, but not globally.  When entities refer to each other in Destiny content, it is this hash that they are referring to.
	Hash int32 `json:"hash,omitempty"`
	// The index of the entity as it was found in the investment tables.
	Index int32 `json:"index,omitempty"`
	// If this is true, then there is an entity with this identifier/type combination, but BNet is not yet allowed to show it. Sorry!
	Redacted bool `json:"redacted,omitempty"`
}

