/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package api





type DestinyHistoricalStatsDestinyClanAggregateStat struct {
	// The id of the mode of stats (allPvp, allPvE, etc)
	Mode *interface{} `json:"mode,omitempty"`
	// The id of the stat
	StatId string `json:"statId,omitempty"`
	// Value of the stat for this player
	Value *interface{} `json:"value,omitempty"`
}

