/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package api




// When a Graph needs to show active Progressions, this defines those objectives as well as an identifier.
type DestinyDefinitionsDirectorDestinyActivityGraphDisplayProgressionDefinition struct {
	
	Id int32 `json:"id,omitempty"`
	
	ProgressionHash int32 `json:"progressionHash,omitempty"`
}

