/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package api




// Many items can be rendered in 3D. When you request this block, you will obtain the custom data needed to render this specific instance of the item.
type DestinyEntitiesItemsDestinyItemRenderComponent struct {
	// If you should use custom dyes on this item, it will be indicated here.
	UseCustomDyes bool `json:"useCustomDyes,omitempty"`
	// A dictionary for rendering gear components, with:  key = Art Arrangement Region Index  value = The chosen Arrangement Index for the Region, based on the value of a stat on the item used for making the choice.
	ArtRegions map[string]int32 `json:"artRegions,omitempty"`
}

