/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package api



// DestinyDestinyItemType : An enumeration that indicates the high-level \"type\" of the item, attempting to iron out the context specific differences for specific instances of an entity. For instance, though a weapon may be of various wepaon \"Types\", in DestinyItemType they are all classified as \"Weapon\". This allows for better filtering on a higher level of abstraction for the concept of types.   This enum is provided for historical compatibility with Destiny 1, but an ideal alternative is to use DestinyItemCategoryDefinitions and the DestinyItemDefinition.itemCategories property instead. Item Categories allow for arbitrary hierarchies of specificity, and for items to belong to multiple categories across multiple hierarchies simultaneously. For this enum, we pick a single type as a \"best guess\" fit.   NOTE: This is not all of the item types available, and some of these are holdovers from Destiny 1 that may or may not still exist.
type DestinyDestinyItemType int32

// Enum DestinyDestinyItemType
const (
	DestinyDestinyItemType_0 DestinyDestinyItemType = 0
	DestinyDestinyItemType_1 DestinyDestinyItemType = 1
	DestinyDestinyItemType_2 DestinyDestinyItemType = 2
	DestinyDestinyItemType_3 DestinyDestinyItemType = 3
	DestinyDestinyItemType_7 DestinyDestinyItemType = 7
	DestinyDestinyItemType_8 DestinyDestinyItemType = 8
	DestinyDestinyItemType_9 DestinyDestinyItemType = 9
	DestinyDestinyItemType_10 DestinyDestinyItemType = 10
	DestinyDestinyItemType_11 DestinyDestinyItemType = 11
	DestinyDestinyItemType_12 DestinyDestinyItemType = 12
	DestinyDestinyItemType_13 DestinyDestinyItemType = 13
	DestinyDestinyItemType_14 DestinyDestinyItemType = 14
	DestinyDestinyItemType_15 DestinyDestinyItemType = 15
	DestinyDestinyItemType_16 DestinyDestinyItemType = 16
	DestinyDestinyItemType_17 DestinyDestinyItemType = 17
	DestinyDestinyItemType_18 DestinyDestinyItemType = 18
	DestinyDestinyItemType_19 DestinyDestinyItemType = 19
)


