/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package api




// Defines a particular entry in an ItemSet (AKA a particular Quest Step in a Quest)
type DestinyDefinitionsDestinyItemSetBlockEntryDefinition struct {
	// Used for tracking which step a user reached. These values will be populated in the user's internal state, which we expose externally as a more usable DestinyQuestStatus object. If this item has been obtained, this value will be set in trackingUnlockValueHash.
	TrackingValue int32 `json:"trackingValue,omitempty"`
	// This is the hash identifier for a DestinyInventoryItemDefinition representing this quest step.
	ItemHash int32 `json:"itemHash,omitempty"`
}

