/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package api




// The response contract for GetDestinyCharacter, with components that can be returned for character and item-level data.
type DestinyResponsesDestinyCharacterResponse struct {
	// The character-level non-equipped inventory items.  COMPONENT TYPE: CharacterInventories
	Inventory *SingleComponentResponseOfDestinyInventoryComponent `json:"inventory,omitempty"`
	// Base information about the character in question.  COMPONENT TYPE: Characters
	Character *interface{} `json:"character,omitempty"`
	// Character progression data, including Milestones.  COMPONENT TYPE: CharacterProgressions
	Progressions *interface{} `json:"progressions,omitempty"`
	// Character rendering data - a minimal set of information about equipment and dyes used for rendering.  COMPONENT TYPE: CharacterRenderData
	RenderData *interface{} `json:"renderData,omitempty"`
	// Activity data - info about current activities available to the player.  COMPONENT TYPE: CharacterActivities
	Activities *interface{} `json:"activities,omitempty"`
	// Equipped items on the character.  COMPONENT TYPE: CharacterEquipment
	Equipment *SingleComponentResponseOfDestinyInventoryComponent `json:"equipment,omitempty"`
	// Items available from Kiosks that are available to this specific character.   COMPONENT TYPE: Kiosks
	Kiosks *interface{} `json:"kiosks,omitempty"`
	// The set of components belonging to the player's instanced items.  COMPONENT TYPE: [See inside the DestinyItemComponentSet contract for component types.]
	ItemComponents *interface{} `json:"itemComponents,omitempty"`
}

