/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package api



// DestinyDestinyProgressionScope : There are many Progressions in Destiny (think Character Level, or Reputation). These are the various \"Scopes\" of Progressions, which affect many things: * Where/if they are stored * How they are calculated * Where they can be used in other game logic
type DestinyDestinyProgressionScope int32

// Enum DestinyDestinyProgressionScope
const (
	DestinyDestinyProgressionScope_0 DestinyDestinyProgressionScope = 0
	DestinyDestinyProgressionScope_1 DestinyDestinyProgressionScope = 1
	DestinyDestinyProgressionScope_2 DestinyDestinyProgressionScope = 2
	DestinyDestinyProgressionScope_3 DestinyDestinyProgressionScope = 3
	DestinyDestinyProgressionScope_4 DestinyDestinyProgressionScope = 4
	DestinyDestinyProgressionScope_5 DestinyDestinyProgressionScope = 5
	DestinyDestinyProgressionScope_6 DestinyDestinyProgressionScope = 6
	DestinyDestinyProgressionScope_7 DestinyDestinyProgressionScope = 7
	DestinyDestinyProgressionScope_8 DestinyDestinyProgressionScope = 8
)


