/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package api




type DestinyDestinySocketVisibility int32

// Enum DestinyDestinySocketVisibility
const (
	DestinyDestinySocketVisibility_0 DestinyDestinySocketVisibility = 0
	DestinyDestinySocketVisibility_1 DestinyDestinySocketVisibility = 1
	DestinyDestinySocketVisibility_2 DestinyDestinySocketVisibility = 2
)


