/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package api



// DestinyDestinyVendorInteractionRewardSelection : When a Vendor Interaction provides rewards, they'll either let you choose one or let you have all of them. This determines which it will be.
type DestinyDestinyVendorInteractionRewardSelection int32

// Enum DestinyDestinyVendorInteractionRewardSelection
const (
	DestinyDestinyVendorInteractionRewardSelection_0 DestinyDestinyVendorInteractionRewardSelection = 0
	DestinyDestinyVendorInteractionRewardSelection_1 DestinyDestinyVendorInteractionRewardSelection = 1
	DestinyDestinyVendorInteractionRewardSelection_2 DestinyDestinyVendorInteractionRewardSelection = 2
)


