/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package api




// If defined, the item has at least one socket.
type DestinyDefinitionsDestinyItemSocketBlockDefinition struct {
	// This was supposed to be a string that would give per-item details about sockets. In practice, it turns out that all this ever has is the localized word \"details\". ... that's lame, but perhaps it will become something cool in the future.
	Detail string `json:"detail,omitempty"`
	// Each socket on an item is defined here. Check inside for more info.
	SocketEntries []DestinyDefinitionsDestinyItemSocketEntryDefinition `json:"socketEntries,omitempty"`
	// A convenience property, that refers to the sockets in the \"sockets\" property, pre-grouped by category and ordered in the manner that they should be grouped in the UI. You could form this yourself with the existing data, but why would you want to? Enjoy life man.
	SocketCategories []DestinyDefinitionsDestinyItemSocketCategoryDefinition `json:"socketCategories,omitempty"`
}

