/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package api




type DestinyHistoricalStatsDefinitionsUnitType int32

// Enum DestinyHistoricalStatsDefinitionsUnitType
const (
	DestinyHistoricalStatsDefinitionsUnitType_0 DestinyHistoricalStatsDefinitionsUnitType = 0
	DestinyHistoricalStatsDefinitionsUnitType_1 DestinyHistoricalStatsDefinitionsUnitType = 1
	DestinyHistoricalStatsDefinitionsUnitType_2 DestinyHistoricalStatsDefinitionsUnitType = 2
	DestinyHistoricalStatsDefinitionsUnitType_3 DestinyHistoricalStatsDefinitionsUnitType = 3
	DestinyHistoricalStatsDefinitionsUnitType_4 DestinyHistoricalStatsDefinitionsUnitType = 4
	DestinyHistoricalStatsDefinitionsUnitType_5 DestinyHistoricalStatsDefinitionsUnitType = 5
	DestinyHistoricalStatsDefinitionsUnitType_6 DestinyHistoricalStatsDefinitionsUnitType = 6
	DestinyHistoricalStatsDefinitionsUnitType_7 DestinyHistoricalStatsDefinitionsUnitType = 7
	DestinyHistoricalStatsDefinitionsUnitType_8 DestinyHistoricalStatsDefinitionsUnitType = 8
	DestinyHistoricalStatsDefinitionsUnitType_9 DestinyHistoricalStatsDefinitionsUnitType = 9
	DestinyHistoricalStatsDefinitionsUnitType_10 DestinyHistoricalStatsDefinitionsUnitType = 10
	DestinyHistoricalStatsDefinitionsUnitType_11 DestinyHistoricalStatsDefinitionsUnitType = 11
	DestinyHistoricalStatsDefinitionsUnitType_12 DestinyHistoricalStatsDefinitionsUnitType = 12
)


