/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package api




// Defines a Character Class in Destiny 2. These are types of characters you can play, like Titan, Warlock, and Hunter.
type DestinyDefinitionsDestinyClassDefinition struct {
	// In Destiny 1, we added a convenience Enumeration for referring to classes. We've kept it, though mostly for posterity. This is the enum value for this definition's class.
	ClassType *interface{} `json:"classType,omitempty"`
	
	DisplayProperties *DestinyDefinitionsCommonDestinyDisplayPropertiesDefinition `json:"displayProperties,omitempty"`
	// A localized string referring to the singular form of the Class's name when referred to in gendered form. Keyed by the DestinyGender.
	GenderedClassNames map[string]string `json:"genderedClassNames,omitempty"`
	// If the Class has a Mentor (all classes *should*), this will be the hash identifier for that Vendor if you care.
	MentorVendorHash int32 `json:"mentorVendorHash,omitempty"`
	// The unique identifier for this entity. Guaranteed to be unique for the type of entity, but not globally.  When entities refer to each other in Destiny content, it is this hash that they are referring to.
	Hash int32 `json:"hash,omitempty"`
	// The index of the entity as it was found in the investment tables.
	Index int32 `json:"index,omitempty"`
	// If this is true, then there is an entity with this identifier/type combination, but BNet is not yet allowed to show it. Sorry!
	Redacted bool `json:"redacted,omitempty"`
}

