/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package api




// Primarily for Quests, this is the definition of properties related to the item if it is a quest and its various quest steps.
type DestinyDefinitionsDestinyItemSetBlockDefinition struct {
	// A collection of hashes of set items, for items such as Quest Metadata items that possess this data.
	ItemList []DestinyDefinitionsDestinyItemSetBlockEntryDefinition `json:"itemList,omitempty"`
	// If true, items in the set can only be added in increasing order, and adding an item will remove any previous item. For Quests, this is by necessity true. Only one quest step is present at a time, and previous steps are removed as you advance in the quest.
	RequireOrderedSetItemAdd bool `json:"requireOrderedSetItemAdd,omitempty"`
	// If true, the UI should treat this quest as \"featured\"
	SetIsFeatured bool `json:"setIsFeatured,omitempty"`
	// A string identifier we can use to attempt to identify the category of the Quest.
	SetType string `json:"setType,omitempty"`
}

