/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package api




// The definition of an item and quantity required in a character's inventory in order to perform an action.
type DestinyDefinitionsDestinyItemActionRequiredItemDefinition struct {
	// The minimum quantity of the item you have to have.
	Count int32 `json:"count,omitempty"`
	// The hash identifier of the item you need to have. Use it to look up the DestinyInventoryItemDefinition for more info.
	ItemHash int32 `json:"itemHash,omitempty"`
	// If true, the item/quantity will be deleted from your inventory when the action is performed. Otherwise, you'll retain these required items after the action is complete.
	DeleteOnAction bool `json:"deleteOnAction,omitempty"`
}

