/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package api

import (
	"time"
)




type DestinyHistoricalStatsDestinyPostGameCarnageReportData struct {
	// Date and time for the activity.
	Period time.Time `json:"period,omitempty"`
	// Details about the activity.
	ActivityDetails *interface{} `json:"activityDetails,omitempty"`
	// Collection of players and their data for this activity.
	Entries []DestinyHistoricalStatsDestinyPostGameCarnageReportEntry `json:"entries,omitempty"`
	// Collection of stats for the player in this activity.
	Teams []DestinyHistoricalStatsDestinyPostGameCarnageReportTeamEntry `json:"teams,omitempty"`
}

