/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package api




// Information about matchmaking and party size for the activity.
type DestinyDefinitionsDestinyActivityMatchmakingBlockDefinition struct {
	// If TRUE, the activity is matchmade. Otherwise, it requires explicit forming of a party.
	IsMatchmade bool `json:"isMatchmade,omitempty"`
	// The minimum # of people in the fireteam for the activity to launch.
	MinParty int32 `json:"minParty,omitempty"`
	// The maximum # of people allowed in a Fireteam.
	MaxParty int32 `json:"maxParty,omitempty"`
	// The maximum # of people allowed across all teams in the activity.
	MaxPlayers int32 `json:"maxPlayers,omitempty"`
	// If true, you have to Solemnly Swear to be up to Nothing But Good(tm) to play.
	RequiresGuardianOath bool `json:"requiresGuardianOath,omitempty"`
}

