/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package api




type DestinyTierType int32

// Enum DestinyTierType
const (
	DestinyTierType_0 DestinyTierType = 0
	DestinyTierType_1 DestinyTierType = 1
	DestinyTierType_2 DestinyTierType = 2
	DestinyTierType_3 DestinyTierType = 3
	DestinyTierType_4 DestinyTierType = 4
	DestinyTierType_5 DestinyTierType = 5
	DestinyTierType_6 DestinyTierType = 6
)


