/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package api




// This Block defines the rendering data associated with the item, if any.
type DestinyDefinitionsDestinyItemTranslationBlockDefinition struct {
	
	WeaponPatternIdentifier string `json:"weaponPatternIdentifier,omitempty"`
	
	WeaponPatternHash int32 `json:"weaponPatternHash,omitempty"`
	
	DefaultDyes []DestinyDyeReference `json:"defaultDyes,omitempty"`
	
	LockedDyes []DestinyDyeReference `json:"lockedDyes,omitempty"`
	
	CustomDyes []DestinyDyeReference `json:"customDyes,omitempty"`
	
	Arrangements []DestinyDefinitionsDestinyGearArtArrangementReference `json:"arrangements,omitempty"`
	
	HasGeometry bool `json:"hasGeometry,omitempty"`
}

