/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package api




// A reference to an Activity Modifier from another entity, such as an Activity (for now, just Activities).  This defines some
type DestinyDefinitionsDestinyActivityModifierReferenceDefinition struct {
	// The hash identifier for the DestinyActivityModifierDefinition referenced by this activity.
	ActivityModifierHash int32 `json:"activityModifierHash,omitempty"`
}

