/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package api




type DestinyBucketScope int32

// Enum DestinyBucketScope
const (
	DestinyBucketScope_0 DestinyBucketScope = 0
	DestinyBucketScope_1 DestinyBucketScope = 1
)


