/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package api




type ForumForumRecruitmentToneLabel int32

// Enum ForumForumRecruitmentToneLabel
const (
	ForumForumRecruitmentToneLabel_0 ForumForumRecruitmentToneLabel = 0
	ForumForumRecruitmentToneLabel_1 ForumForumRecruitmentToneLabel = 1
	ForumForumRecruitmentToneLabel_2 ForumForumRecruitmentToneLabel = 2
)


