/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package api





type ForumForumRecruitmentDetail struct {
	
	TopicId int64 `json:"topicId,omitempty"`
	
	MicrophoneRequired bool `json:"microphoneRequired,omitempty"`
	
	Intensity *ForumForumRecruitmentIntensityLabel `json:"intensity,omitempty"`
	
	Tone *ForumForumRecruitmentToneLabel `json:"tone,omitempty"`
	
	Approved bool `json:"approved,omitempty"`
	
	ConversationId int64 `json:"conversationId,omitempty"`
	
	PlayerSlotsTotal int32 `json:"playerSlotsTotal,omitempty"`
	
	PlayerSlotsRemaining int32 `json:"playerSlotsRemaining,omitempty"`
	
	Fireteam []UserGeneralUser `json:"Fireteam,omitempty"`
	
	KickedPlayerIds []int64 `json:"kickedPlayerIds,omitempty"`
}

