/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package api




type ForumForumTopicsSortEnum int32

// Enum ForumForumTopicsSortEnum
const (
	ForumForumTopicsSortEnum_0 ForumForumTopicsSortEnum = 0
	ForumForumTopicsSortEnum_1 ForumForumTopicsSortEnum = 1
	ForumForumTopicsSortEnum_2 ForumForumTopicsSortEnum = 2
	ForumForumTopicsSortEnum_3 ForumForumTopicsSortEnum = 3
	ForumForumTopicsSortEnum_4 ForumForumTopicsSortEnum = 4
	ForumForumTopicsSortEnum_5 ForumForumTopicsSortEnum = 5
	ForumForumTopicsSortEnum_6 ForumForumTopicsSortEnum = 6
	ForumForumTopicsSortEnum_7 ForumForumTopicsSortEnum = 7
)


