/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package api




type ForumForumMediaType int32

// Enum ForumForumMediaType
const (
	ForumForumMediaType_0 ForumForumMediaType = 0
	ForumForumMediaType_1 ForumForumMediaType = 1
	ForumForumMediaType_2 ForumForumMediaType = 2
	ForumForumMediaType_3 ForumForumMediaType = 3
)


