/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package api




type ForumForumPostPopularity int32

// Enum ForumForumPostPopularity
const (
	ForumForumPostPopularity_0 ForumForumPostPopularity = 0
	ForumForumPostPopularity_1 ForumForumPostPopularity = 1
	ForumForumPostPopularity_2 ForumForumPostPopularity = 2
	ForumForumPostPopularity_3 ForumForumPostPopularity = 3
	ForumForumPostPopularity_4 ForumForumPostPopularity = 4
	ForumForumPostPopularity_5 ForumForumPostPopularity = 5
)


