/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package api




type ForumForumTopicsCategoryFiltersEnum int32

// Enum ForumForumTopicsCategoryFiltersEnum
const (
	ForumForumTopicsCategoryFiltersEnum_0 ForumForumTopicsCategoryFiltersEnum = 0
	ForumForumTopicsCategoryFiltersEnum_1 ForumForumTopicsCategoryFiltersEnum = 1
	ForumForumTopicsCategoryFiltersEnum_2 ForumForumTopicsCategoryFiltersEnum = 2
	ForumForumTopicsCategoryFiltersEnum_4 ForumForumTopicsCategoryFiltersEnum = 4
	ForumForumTopicsCategoryFiltersEnum_8 ForumForumTopicsCategoryFiltersEnum = 8
	ForumForumTopicsCategoryFiltersEnum_16 ForumForumTopicsCategoryFiltersEnum = 16
	ForumForumTopicsCategoryFiltersEnum_32 ForumForumTopicsCategoryFiltersEnum = 32
	ForumForumTopicsCategoryFiltersEnum_64 ForumForumTopicsCategoryFiltersEnum = 64
	ForumForumTopicsCategoryFiltersEnum_128 ForumForumTopicsCategoryFiltersEnum = 128
)


