/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package api




type ForumForumFlagsEnum int32

// Enum ForumForumFlagsEnum
const (
	ForumForumFlagsEnum_0 ForumForumFlagsEnum = 0
	ForumForumFlagsEnum_1 ForumForumFlagsEnum = 1
	ForumForumFlagsEnum_2 ForumForumFlagsEnum = 2
	ForumForumFlagsEnum_4 ForumForumFlagsEnum = 4
	ForumForumFlagsEnum_8 ForumForumFlagsEnum = 8
	ForumForumFlagsEnum_16 ForumForumFlagsEnum = 16
	ForumForumFlagsEnum_32 ForumForumFlagsEnum = 32
	ForumForumFlagsEnum_64 ForumForumFlagsEnum = 64
	ForumForumFlagsEnum_128 ForumForumFlagsEnum = 128
)


