/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package api




type GroupsV2GroupAllianceStatus int32

// Enum GroupsV2GroupAllianceStatus
const (
	GroupsV2GroupAllianceStatus_0 GroupsV2GroupAllianceStatus = 0
	GroupsV2GroupAllianceStatus_1 GroupsV2GroupAllianceStatus = 1
	GroupsV2GroupAllianceStatus_2 GroupsV2GroupAllianceStatus = 2
)


