/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package api





type GroupsV2GroupFeatures struct {
	
	MaximumMembers int32 `json:"maximumMembers,omitempty"`
	// Maximum number of groups of this type a typical membership may join. For example, a user may join about 50 General groups with their Bungie.net account. They may join one clan per Destiny membership.
	MaximumMembershipsOfGroupType int32 `json:"maximumMembershipsOfGroupType,omitempty"`
	
	Capabilities *GroupsV2Capabilities `json:"capabilities,omitempty"`
	
	MembershipTypes []BungieMembershipType `json:"membershipTypes,omitempty"`
	// Minimum Member Level allowed to invite new members to group  Always Allowed: Founder, Acting Founder  True means admins have this power, false means they don't  Default is false for clans, true for groups.
	InvitePermissionOverride bool `json:"invitePermissionOverride,omitempty"`
	// Minimum Member Level allowed to update group culture  Always Allowed: Founder, Acting Founder  True means admins have this power, false means they don't  Default is false for clans, true for groups.
	UpdateCulturePermissionOverride bool `json:"updateCulturePermissionOverride,omitempty"`
	// Minimum Member Level allowed to host guided games  Always Allowed: Founder, Acting Founder, Admin  Allowed Overrides: None, Member, Beginner  Default is Member for clans, None for groups, although this means nothing for groups.
	HostGuidedGamePermissionOverride *interface{} `json:"hostGuidedGamePermissionOverride,omitempty"`
	// Minimum Member Level allowed to update banner  Always Allowed: Founder, Acting Founder  True means admins have this power, false means they don't  Default is false for clans, true for groups.
	UpdateBannerPermissionOverride bool `json:"updateBannerPermissionOverride,omitempty"`
	// Level to join a member at when accepting an invite, application, or joining an open clan  Default is Beginner.
	JoinLevel *interface{} `json:"joinLevel,omitempty"`
}

