/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package api





type GroupsV2GroupOptionsEditAction struct {
	// Minimum Member Level allowed to invite new members to group  Always Allowed: Founder, Acting Founder  True means admins have this power, false means they don't  Default is false for clans, true for groups.
	InvitePermissionOverride bool `json:"InvitePermissionOverride,omitempty"`
	// Minimum Member Level allowed to update group culture  Always Allowed: Founder, Acting Founder  True means admins have this power, false means they don't  Default is false for clans, true for groups.
	UpdateCulturePermissionOverride bool `json:"UpdateCulturePermissionOverride,omitempty"`
	// Minimum Member Level allowed to host guided games  Always Allowed: Founder, Acting Founder, Admin  Allowed Overrides: None, Member, Beginner  Default is Member for clans, None for groups, although this means nothing for groups.
	HostGuidedGamePermissionOverride int32 `json:"HostGuidedGamePermissionOverride,omitempty"`
	// Minimum Member Level allowed to update banner  Always Allowed: Founder, Acting Founder  True means admins have this power, false means they don't  Default is false for clans, true for groups.
	UpdateBannerPermissionOverride bool `json:"UpdateBannerPermissionOverride,omitempty"`
	// Level to join a member at when accepting an invite, application, or joining an open clan  Default is Beginner.
	JoinLevel int32 `json:"JoinLevel,omitempty"`
}

