/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package api

import (
	"time"
)




type GroupsV2GroupMemberApplication struct {
	
	GroupId int64 `json:"groupId,omitempty"`
	
	CreationDate time.Time `json:"creationDate,omitempty"`
	
	ResolveState *GroupsV2GroupApplicationResolveState `json:"resolveState,omitempty"`
	
	ResolveDate time.Time `json:"resolveDate,omitempty"`
	
	ResolvedByMembershipId int64 `json:"resolvedByMembershipId,omitempty"`
	
	RequestMessage string `json:"requestMessage,omitempty"`
	
	ResolveMessage string `json:"resolveMessage,omitempty"`
	
	DestinyUserInfo *UserUserInfoCard `json:"destinyUserInfo,omitempty"`
	
	BungieNetUserInfo *UserUserInfoCard `json:"bungieNetUserInfo,omitempty"`
}

