/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package api




type GroupsV2Capabilities int32

// Enum GroupsV2Capabilities
const (
	GroupsV2Capabilities_0 GroupsV2Capabilities = 0
	GroupsV2Capabilities_1 GroupsV2Capabilities = 1
	GroupsV2Capabilities_2 GroupsV2Capabilities = 2
	GroupsV2Capabilities_4 GroupsV2Capabilities = 4
	GroupsV2Capabilities_8 GroupsV2Capabilities = 8
	GroupsV2Capabilities_16 GroupsV2Capabilities = 16
	GroupsV2Capabilities_32 GroupsV2Capabilities = 32
	GroupsV2Capabilities_64 GroupsV2Capabilities = 64
)


