/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package api



// GroupsV2HostGuidedGamesPermissionLevel : Used for setting the guided game permission level override (admins and founders can always host guided games).
type GroupsV2HostGuidedGamesPermissionLevel int32

// Enum GroupsV2HostGuidedGamesPermissionLevel
const (
	GroupsV2HostGuidedGamesPermissionLevel_0 GroupsV2HostGuidedGamesPermissionLevel = 0
	GroupsV2HostGuidedGamesPermissionLevel_1 GroupsV2HostGuidedGamesPermissionLevel = 1
	GroupsV2HostGuidedGamesPermissionLevel_2 GroupsV2HostGuidedGamesPermissionLevel = 2
)


