/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package api





type GroupsV2GroupAction struct {
	// Type of group, either Bungie.net hosted group, or a game services hosted clan.
	GroupType *interface{} `json:"groupType,omitempty"`
	
	Name string `json:"name,omitempty"`
	
	About string `json:"about,omitempty"`
	
	Motto string `json:"motto,omitempty"`
	
	Theme string `json:"theme,omitempty"`
	
	AvatarImageIndex int32 `json:"avatarImageIndex,omitempty"`
	
	Tags string `json:"tags,omitempty"`
	
	IsPublic bool `json:"isPublic,omitempty"`
	
	MembershipOption *GroupsV2MembershipOption `json:"membershipOption,omitempty"`
	
	IsPublicTopicAdminOnly bool `json:"isPublicTopicAdminOnly,omitempty"`
	
	IsDefaultPostPublic bool `json:"isDefaultPostPublic,omitempty"`
	
	AllowChat bool `json:"allowChat,omitempty"`
	
	IsDefaultPostAlliance bool `json:"isDefaultPostAlliance,omitempty"`
	
	ChatSecurity *GroupsV2ChatSecuritySetting `json:"chatSecurity,omitempty"`
	
	Callsign string `json:"callsign,omitempty"`
	
	Locale string `json:"locale,omitempty"`
	
	Homepage *GroupsV2GroupHomepage `json:"homepage,omitempty"`
	// When operation needs a platform specific account ID for the present user, use this property. In particular, groupType of Clan requires this value to be set.
	PlatformMembershipType *interface{} `json:"platformMembershipType,omitempty"`
}

