/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package api




type GroupsV2ChatSecuritySetting int32

// Enum GroupsV2ChatSecuritySetting
const (
	GroupsV2ChatSecuritySetting_0 GroupsV2ChatSecuritySetting = 0
	GroupsV2ChatSecuritySetting_1 GroupsV2ChatSecuritySetting = 1
)


