/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package api




type GroupsV2GroupMemberCountFilter int32

// Enum GroupsV2GroupMemberCountFilter
const (
	GroupsV2GroupMemberCountFilter_0 GroupsV2GroupMemberCountFilter = 0
	GroupsV2GroupMemberCountFilter_1 GroupsV2GroupMemberCountFilter = 1
	GroupsV2GroupMemberCountFilter_2 GroupsV2GroupMemberCountFilter = 2
	GroupsV2GroupMemberCountFilter_3 GroupsV2GroupMemberCountFilter = 3
)


