/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package api




type GroupsV2GroupHomepage int32

// Enum GroupsV2GroupHomepage
const (
	GroupsV2GroupHomepage_0 GroupsV2GroupHomepage = 0
	GroupsV2GroupHomepage_1 GroupsV2GroupHomepage = 1
	GroupsV2GroupHomepage_2 GroupsV2GroupHomepage = 2
)


