/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package api




type GroupsV2GroupSortBy int32

// Enum GroupsV2GroupSortBy
const (
	GroupsV2GroupSortBy_0 GroupsV2GroupSortBy = 0
	GroupsV2GroupSortBy_1 GroupsV2GroupSortBy = 1
	GroupsV2GroupSortBy_2 GroupsV2GroupSortBy = 2
	GroupsV2GroupSortBy_3 GroupsV2GroupSortBy = 3
)


