/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package api

import (
	"time"
)




type GroupsV2GroupV2 struct {
	
	GroupId int64 `json:"groupId,omitempty"`
	
	Name string `json:"name,omitempty"`
	
	GroupType *GroupsV2GroupType `json:"groupType,omitempty"`
	
	MembershipIdCreated int64 `json:"membershipIdCreated,omitempty"`
	
	CreationDate time.Time `json:"creationDate,omitempty"`
	
	ModificationDate time.Time `json:"modificationDate,omitempty"`
	
	About string `json:"about,omitempty"`
	
	Tags []string `json:"tags,omitempty"`
	
	MemberCount int32 `json:"memberCount,omitempty"`
	
	IsPublic bool `json:"isPublic,omitempty"`
	
	IsPublicTopicAdminOnly bool `json:"isPublicTopicAdminOnly,omitempty"`
	
	PrimaryAlliedGroupId int64 `json:"primaryAlliedGroupId,omitempty"`
	
	Motto string `json:"motto,omitempty"`
	
	AllowChat bool `json:"allowChat,omitempty"`
	
	IsDefaultPostPublic bool `json:"isDefaultPostPublic,omitempty"`
	
	ChatSecurity *GroupsV2ChatSecuritySetting `json:"chatSecurity,omitempty"`
	
	Locale string `json:"locale,omitempty"`
	
	AvatarImageIndex int32 `json:"avatarImageIndex,omitempty"`
	
	Homepage *GroupsV2GroupHomepage `json:"homepage,omitempty"`
	
	MembershipOption *GroupsV2MembershipOption `json:"membershipOption,omitempty"`
	
	DefaultPublicity *GroupsV2GroupPostPublicity `json:"defaultPublicity,omitempty"`
	
	Theme string `json:"theme,omitempty"`
	
	BannerPath string `json:"bannerPath,omitempty"`
	
	AvatarPath string `json:"avatarPath,omitempty"`
	
	IsAllianceOwner bool `json:"isAllianceOwner,omitempty"`
	
	ConversationId int64 `json:"conversationId,omitempty"`
	
	EnableInvitationMessagingForAdmins bool `json:"enableInvitationMessagingForAdmins,omitempty"`
	
	BanExpireDate time.Time `json:"banExpireDate,omitempty"`
	
	Features *GroupsV2GroupFeatures `json:"features,omitempty"`
	
	ClanInfo *GroupsV2GroupV2ClanInfoAndInvestment `json:"clanInfo,omitempty"`
}

