/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package api




type GroupsV2GroupApplicationResolveState int32

// Enum GroupsV2GroupApplicationResolveState
const (
	GroupsV2GroupApplicationResolveState_0 GroupsV2GroupApplicationResolveState = 0
	GroupsV2GroupApplicationResolveState_1 GroupsV2GroupApplicationResolveState = 1
	GroupsV2GroupApplicationResolveState_2 GroupsV2GroupApplicationResolveState = 2
	GroupsV2GroupApplicationResolveState_3 GroupsV2GroupApplicationResolveState = 3
)


