/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package api





type GroupsV2GroupEditAction struct {
	
	Name string `json:"name,omitempty"`
	
	About string `json:"about,omitempty"`
	
	Motto string `json:"motto,omitempty"`
	
	Theme string `json:"theme,omitempty"`
	
	AvatarImageIndex int32 `json:"avatarImageIndex,omitempty"`
	
	Tags string `json:"tags,omitempty"`
	
	IsPublic bool `json:"isPublic,omitempty"`
	
	MembershipOption int32 `json:"membershipOption,omitempty"`
	
	IsPublicTopicAdminOnly bool `json:"isPublicTopicAdminOnly,omitempty"`
	
	AllowChat bool `json:"allowChat,omitempty"`
	
	ChatSecurity int32 `json:"chatSecurity,omitempty"`
	
	Callsign string `json:"callsign,omitempty"`
	
	Locale string `json:"locale,omitempty"`
	
	Homepage int32 `json:"homepage,omitempty"`
	
	EnableInvitationMessagingForAdmins bool `json:"enableInvitationMessagingForAdmins,omitempty"`
	
	DefaultPublicity int32 `json:"defaultPublicity,omitempty"`
}

