/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package api




type GroupsV2GroupsForMemberFilter int32

// Enum GroupsV2GroupsForMemberFilter
const (
	GroupsV2GroupsForMemberFilter_0 GroupsV2GroupsForMemberFilter = 0
	GroupsV2GroupsForMemberFilter_1 GroupsV2GroupsForMemberFilter = 1
	GroupsV2GroupsForMemberFilter_2 GroupsV2GroupsForMemberFilter = 2
)


