/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package api





type GroupsV2GroupOptionalConversation struct {
	
	GroupId int64 `json:"groupId,omitempty"`
	
	ConversationId int64 `json:"conversationId,omitempty"`
	
	ChatEnabled bool `json:"chatEnabled,omitempty"`
	
	ChatName string `json:"chatName,omitempty"`
	
	ChatSecurity *GroupsV2ChatSecuritySetting `json:"chatSecurity,omitempty"`
}

