/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package api




type IgnoresIgnoreStatus int32

// Enum IgnoresIgnoreStatus
const (
	IgnoresIgnoreStatus_0 IgnoresIgnoreStatus = 0
	IgnoresIgnoreStatus_1 IgnoresIgnoreStatus = 1
	IgnoresIgnoreStatus_2 IgnoresIgnoreStatus = 2
	IgnoresIgnoreStatus_4 IgnoresIgnoreStatus = 4
	IgnoresIgnoreStatus_8 IgnoresIgnoreStatus = 8
	IgnoresIgnoreStatus_16 IgnoresIgnoreStatus = 16
	IgnoresIgnoreStatus_32 IgnoresIgnoreStatus = 32
)


