/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package api




type IgnoresIgnoreLength int32

// Enum IgnoresIgnoreLength
const (
	IgnoresIgnoreLength_0 IgnoresIgnoreLength = 0
	IgnoresIgnoreLength_1 IgnoresIgnoreLength = 1
	IgnoresIgnoreLength_2 IgnoresIgnoreLength = 2
	IgnoresIgnoreLength_3 IgnoresIgnoreLength = 3
	IgnoresIgnoreLength_4 IgnoresIgnoreLength = 4
	IgnoresIgnoreLength_5 IgnoresIgnoreLength = 5
	IgnoresIgnoreLength_6 IgnoresIgnoreLength = 6
	IgnoresIgnoreLength_7 IgnoresIgnoreLength = 7
	IgnoresIgnoreLength_8 IgnoresIgnoreLength = 8
	IgnoresIgnoreLength_9 IgnoresIgnoreLength = 9
	IgnoresIgnoreLength_10 IgnoresIgnoreLength = 10
	IgnoresIgnoreLength_11 IgnoresIgnoreLength = 11
)


