/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package api



// PartnershipsPartnershipType : Representing external partners to which BNet users can link accounts, but that are not Account System credentials: partnerships that BNet uses exclusively for data.
type PartnershipsPartnershipType int32

// Enum PartnershipsPartnershipType
const (
	PartnershipsPartnershipType_0 PartnershipsPartnershipType = 0
	PartnershipsPartnershipType_1 PartnershipsPartnershipType = 1
)


