/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package api





type TrendingTrendingEntryCommunityCreation struct {
	
	Media string `json:"media,omitempty"`
	
	Title string `json:"title,omitempty"`
	
	Author string `json:"author,omitempty"`
	
	AuthorMembershipId int64 `json:"authorMembershipId,omitempty"`
	
	PostId int32 `json:"postId,omitempty"`
	
	Body string `json:"body,omitempty"`
	
	Upvotes int32 `json:"upvotes,omitempty"`
}

