/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package api



// TrendingTrendingEntryType : The known entity types that you can have returned from Trending.
type TrendingTrendingEntryType int32

// Enum TrendingTrendingEntryType
const (
	TrendingTrendingEntryType_0 TrendingTrendingEntryType = 0
	TrendingTrendingEntryType_1 TrendingTrendingEntryType = 1
	TrendingTrendingEntryType_2 TrendingTrendingEntryType = 2
	TrendingTrendingEntryType_3 TrendingTrendingEntryType = 3
	TrendingTrendingEntryType_4 TrendingTrendingEntryType = 4
	TrendingTrendingEntryType_5 TrendingTrendingEntryType = 5
	TrendingTrendingEntryType_6 TrendingTrendingEntryType = 6
	TrendingTrendingEntryType_7 TrendingTrendingEntryType = 7
	TrendingTrendingEntryType_8 TrendingTrendingEntryType = 8
	TrendingTrendingEntryType_9 TrendingTrendingEntryType = 9
)


