/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package api





type UserUserMembershipData struct {
	// this allows you to see destiny memberships that are visible and linked to this account (regardless of whether or not they have characters on the world server)
	DestinyMemberships []UserUserInfoCard `json:"destinyMemberships,omitempty"`
	
	BungieNetUser *UserGeneralUser `json:"bungieNetUser,omitempty"`
}

