/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package api





type UserAckState struct {
	// Indicates the related item has not been acknowledged.
	NeedsAck bool `json:"needsAck,omitempty"`
	// Identifier to use when acknowledging the related item. [category]:[entityId]:[targetId]
	AckId string `json:"ackId,omitempty"`
}

